### ISSUE TITLE
`server.listen()` called after `server.close()` does not mock response

### ISSUE THREAD

**Issue by vishakha94** [kettanaito/msw#2370] opened 2024-11-28 00:57 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v2.6.6

### Reproduction repository

https://github.com/vishakha94/msw/commit/b90344e7090155bbb09909482977dcc353bdcaf2

### Reproduction steps

`npm run test:node`

### Current behavior

We have a NextJS app that implements mocking using feature flag. When we switch the flag off for mocking, we call server.close() and if the feature flag is enabled again, serve.listen() is called.
I observed the following:
1. the first call to server.listen() mocks API properly
2. The second call to server.listen() after server.close() does not mock API

Our NextJS app setup is complicated, but I was able to reproduce the issue here: https://github.com/vishakha94/msw/tree/repro-server-close

I ran `npm run test:node` 

### Expected behavior

Expect for MSW to resume mocking after server.listen() is called after sever.close().

**Comment by kettanaito** [comment] 2024-12-06 12:07
Hi, @vishakha94. Thanks for reporting this.

I was able to reproduce this issue in isolation in https://github.com/mswjs/msw/pull/2383. Will take a look at whats's wrong once I have a moment.

**Comment by kettanaito** [comment] 2024-12-06 12:46
## Root cause

Calling `server.close()` triggers [`this.emitter.removeAllListeners()`](https://github.com/mswjs/interceptors/blob/c338da8363660fbd08e794511e35678dae095670/src/Interceptor.ts#L228) on the interceptor. Starting the server again doesn't seem to attach those listeners again, causing no `request` listener to be present to handle the intercepted request.

**Comment by kettanaito** [comment] 2024-12-06 12:50
I've pushed the fix to the PR. Once the CI is green, I will merge it.

**Closed as completed** 2024-12-06 12:57 UTC
Labels: bug, scope:node

**Comment by kettanaito** [comment] 2024-12-07 01:40
## Released: v2.6.8 🎉

This has been released in v2.6.8!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.6.8)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.6.8)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by vishakha94** [comment] 2024-12-07 19:41
Thanks @kettanaito!
