### ISSUE TITLE
FetchError: "rightFn" is not a function

### ISSUE THREAD

**Issue by BDulieu** [kettanaito/msw#993] opened 2021-11-21 23:50 UTC
## Describe the bug

When running a test in our jest environment we get a FetchError regarding rightFn not being a function. Should this function not already exist and have been implemented using mock service worker?

## Environment

- `msw: 0.34.0`
- `nodejs: 16.13`
- `npm: 6.14.15`
- `jest: 27.3.1`

## Expected behavior
rightFn to be already implemented using mock service worker

## Screenshots
If applicable, add screenshots to help explain your problem

![Screenshot 2021-11-22 105121](https://user-images.githubusercontent.com/86298231/142784024-de2e6cc4-5094-431f-b76b-a05bcb09f721.png)

**Comment by kettanaito** [comment] 2021-11-23 10:59
Hi, @BDulieu. Could you please prepare a reproduction repository where we could look into this? 

This issue doesn't surface in numerous test suits we have, so it may be something specific to what you're doing. That's where it's crucial for us to see how you make requests, how you define request handlers, which environments and polyfills you're using. Preparing a reproduction repository will be the fastest way for us to do so. Thanks.

**Comment by kettanaito** [comment] 2021-12-06 10:46
The stack trace points to this line in the `@mswjs/interceptors` as the last one:

https://github.com/mswjs/interceptors/blob/5b6497000ebf97101eecc680ed6cce58b939e419/src/interceptors/ClientRequest/createClientRequestOverride.ts#L196

This means that your request handling middleware has thrown an exception. That's likely caused by your request handlers producing an exception. I cannot be of more help without a proper reproduction repository. I'm closing this issue as non-reproducible. You can post the link to the GitHub repo where I can look into it at any time. Thanks.

**Closed as completed by kettanaito** 2021-12-06 10:46 UTC
Labels: bug, needs:reproduction

**Comment by michaelphines-stripe** [comment] 2022-07-26 18:12
I got this when I forgot to wrap my response in a ResponseTransformer.

e.g. I had 
```js
    server.use(rest.get(url, (_req, res, ctx) => res(ctx.status(200), generateResponse())));
```
but I needed
```js
    server.use(rest.get(url, (_req, res, ctx) => res(ctx.status(200), ctx.json(generateResponse()))));
```

**Comment by michaelphines** [comment] 2022-07-26 18:14
I got this when I forgot to wrap my response in a ResponseTransformer.

e.g. I had 
```js
    server.use(rest.get(url, (_req, res, ctx) => res(ctx.status(200), generateResponse())));
```
but I needed
```js
    server.use(rest.get(url, (_req, res, ctx) => res(ctx.status(200), ctx.json(generateResponse()))));
```

I wonder if this is predictable and common enough to justify building an explicit error message to throw.
