### ISSUE TITLE
Cyclic object value 

### ISSUE THREAD

**Issue by jmverges** [kettanaito/msw#1151] opened 2022-03-08 12:17 UTC
## Describe the bug
My schema has a to objects that are reciprocal N:N conected like a customer has contacts and each contact has customers and you can access from one to the other. I'm getting TypeError: cyclic object value: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value 
Can this be handled from MSW somehow? Regards.

## Environment

- `msw: 0.35.0`
- `nodejs: v17.4.0`
- `npm: 8.3.1`
- `nuxt 3`
- `vite`

> Please also provide your browser version.

Firefox 98.0b

## To Reproduce
```
type ObjectA{
id: ID
objectsB:[ObjectB]
}
type ObjectB{
id: ID
objectsA:[ObjectA]
}
```
## Expected behavior
If I'm not asking for ObjectB.objectsA.objectsB in my query just don't get the data cycled.

**Comment by kettanaito** [comment] 2022-03-08 13:21
Hey, @jmverges. Thanks for reporting this. 

I'd kindly ask you to provide more info on the issue, specifically:

1. Include your request handlers (how you use MSW);
2. Include the GraphQL query you're making (thanks for including the types!);
3. Include the exact error message you're getting (don't forget the stack trace);
4. Prepare a reproduction repository where I can run and reproduce this behavior. 

I cannot help you much otherwise, so I'm closing the issue until it's in a reproducible state. 

Also, I've noticed you're running an old version of `msw`. Please update via `npm i msw@latest` and see if the issue is still there. If it is, please provide with additional info I've mentioned above. Thanks. 

The most I can do is to assume what is going wrong. From the look of it, I see nothing related to MSW that'd cause this issue.

**Closed as completed by kettanaito** 2022-03-08 13:21 UTC
Labels: bug, needs:reproduction

**Comment by grzuy** [comment] 2022-03-23 12:08
Hi, thanks for your work on this library!

I am experiencing similar issue when feeding data with circular references to `ctx.json`.

```ts
  // In a handler

  const data = db.model.findMany(query); // Using mswjs/data
  return res(ctx.json(data));
}
```

I guess it relates to the fact that `ctx.json` uses `JSON.stringify`?
Similar issue to https://github.com/mswjs/data/pull/163?

Thanks!

**Comment by srosato** [comment] 2022-06-10 04:37
There are libraries like [flatted](https://github.com/WebReflection/flatted) that can stringify a circular json object and then parse it back to a normal object without too much performance overhead. I tried writing a custom `ResponseTransformer` that would use `flatted`, but the thing is, we cannot use `JSON.parse` with a json string that has been stringified by flatted, it must be used by the `stringify` function supplied by flatted.

For exemple, my response transformer looks like this

```typescript
import { stringify } from 'flatted';

export const json = <BodyTypeJSON>(
  body: BodyTypeJSON,
): ResponseTransformer<BodyTypeJSON> => {
  return (res) => {
    res.headers.set('Content-Type', 'application/json')
    res.body = stringify(body)

    return res
  }
}
```

Right now I am trying to find where I can also parse back that string within msw, but I cannot seem to find where. Feels like the json is parsed at the top level within `setupWorker.ts`

**Comment by srosato** [comment] 2022-06-10 05:54
Nevermind, actually, if we want to parse back that json it needs to be done with the client that fetches the data.

For example I am using `graphql-request` and since March they added the support for a custom jsonSerializer (https://github.com/prisma-labs/graphql-request/pull/324).

Therefore it is possible to transform back that circular json that was transformed by `flatten`.

```typescript
import { parse } from 'flatted';

// ... 

new GraphQLClient(getGraphqlUrl(app), {
  headers: {
    'Content-Type': 'application/json'
  },
  jsonSerializer: {
    parse(obj: string): unknown {
      return parse(obj)
    },
    stringify(obj: any): string {
      return JSON.stringify(obj)
    }
  }
});
```
