### ISSUE TITLE
Failed to parse a stored cookie from localStorage (virtual-cookie)

### ISSUE THREAD

**Issue by ghost** [kettanaito/msw#1590] opened 2023-04-11 18:17 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.19.1

### Reproduction repository

https://codesandbox.io/s/msw-react-xx1c8

### Reproduction steps

N/A

### Current behavior

When running tests in our project, we keep getting this virtual-cookie warning in the CLI. Running with Jest 27.5.1 and React Testing Library 12.1.4. Nothing noted in docs/GitHub issues about how to fix this warning.

![Screenshot 2023-04-11 at 12 17 14 PM](https://user-images.githubusercontent.com/127779759/231253718-40eb73cb-8c86-4691-a676-80ba085b4fec.png)

### Expected behavior

Tests run without a console warning.

**Comment by kettanaito** [comment] 2023-04-19 21:15
Hi, @tyler-zieske. Thanks for reporting this. I couldn't find the reproduction for this issue, it looks like you've linked our default sandbox instead. If that was a mistake, please fork that sandbox and add the relevant code that allows me to reproduce this cookie issue. Until then, I will close it. 

The warning implies that the value stored in the cookie is invalid. Please double-check what cookie you are constructing (e.g. the correctness of it if you're doing it manually, or the correctness of using a third-party library if you do so). It's likely you're constructing a cookie string that is invalid. I assume the issue may be that you are not passing a cookie _string_ but instead an object:

```js
headers: {
  // Or something similar. This is an invalid cookie. 
  'Set-Cookie': { accessToken: 'abc-123' }
}
```

**Closed as completed by kettanaito** 2023-04-19 21:15 UTC
Labels: bug, scope:node, needs:triage

**Comment by jasonsilvers-dispel** [comment] 2023-09-08 21:16
I am also running into this issue. I think it comes from when attempting to mock `Storage`

```
jest
      .spyOn(Storage.prototype, 'getItem')
      .mockReturnValue(JSON.stringify({ token: 'abc123' }));
```

From the error it looks like MSW has a key "MSW_COOKIE_STORE" and because it's a global mock it isn't returning a cookie. It's returning the mocked "token"

Is there any way to work around it?
