### ISSUE TITLE
Upgrade to 0.42.0 breaks intercepting node fetch requests

### ISSUE THREAD

**Issue by viktomas** [kettanaito/msw#1264] opened 2022-05-31 06:20 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

14-slim docker image (currently 14.19.3

### Reproduction repository

https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/merge_requests/574

### Reproduction steps

https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/merge_requests/574

1. Checkout the `main` branch (uses msw 0.41.0)
2. run `npm install`
3. run `npm run test-integration`
4. It works

1. checkout the renovate MR branch:

    ```
    git fetch "git@gitlab.com:gitlab-renovate-forks/gitlab-vscode-extension.git" 'renovate/msw-0.x'
    git checkout -b 'gitlab-vscode-extension-renovate/msw-0.x' FETCH_HEAD
    ```

1. now your msw version is 0.42.0
2. run `npm install`
3. run `npm run test-integration`
4. the tests start failing because the testing address `https://test.gitlab.com` doesn't get intercepted anymore

### Current behavior

Intercepting fails with `getaddrinfo ENOTFOUND test.gitlab.com`

### Expected behavior

Intercepting works

**Comment by viktomas** [comment] 2022-05-31 06:25
Thanks for the fantastic work 🙏 I assumed that this issue is so broad that multiple people will face it and that it will be trivial to reproduce on node 14. If it's something more tricky to reproduce, I can create a test project with only a few dependencies and one test.

**Comment by kettanaito** [comment] 2022-05-31 10:34
Hey, @viktomas. Thanks for reporting this!

A couple of latest releases have been bumpy but, trust me, I'm tackling those. It will be worth it in the long run but may cause some issues along the migration path. 

0.42.0 updates the Interceptors library, which migrates in-Node.js interception to an event-based model. I'm curious to look into your reproduction case and see what it's doing that our tests weren't able to cover.

**Comment by viktomas** [comment] 2022-05-31 12:08
I tried to create a simple reproduction scenario and failed: https://gitlab.com/viktomas/reproduce-msw

Also, I was wrong in the original report. I didn't realize that all the integration tests run inside VS Code which is running on node`16.13.0`.

But the simple reproduction scenario still works even on node `16.13.0` 🤔 maybe VS Code does something non-standard?...

**Comment by kettanaito** [comment] 2022-06-09 12:47
Hey, @viktomas. Sorry, I've tried debugging your tests but I just lack the context to do that efficiently. For some reason, neither linking my local `msw` nor editing the installed one makes any difference in the test run. I've made sure I re-compiled the tests, still nothing. 

I can share my thoughts about this issue but I'm afraid I cannot help you much with it unless I have an isolated reproduction repository to look at. 

## Thoughts

So, what we know:

- Requests don't get intercepted;
- We see the unhandled request warnings.

Both are related. It looks like MSW can't find a matching handler for the requests that happen. This handler lookup consists of two phases, and happens here:

https://github.com/mswjs/msw/blob/e531c35b51b6c785985e19d3fe85ec6ac7f10f53/src/utils/getResponse.ts#L31

First, a simple URL/operation type/name predicate check against an intercepted request.

https://github.com/mswjs/msw/blob/e531c35b51b6c785985e19d3fe85ec6ac7f10f53/src/utils/getResponse.ts#L50

Then, any handlers that passed the predicate run themselves. This calls resolver functions and awaits their return. However, I think in your case the `result` of that resolver execution will be `null`, so the next branch triggers:

https://github.com/mswjs/msw/blob/e531c35b51b6c785985e19d3fe85ec6ac7f10f53/src/utils/getResponse.ts#L72-L80

> Also, I've spotted you have a few places where you forget to return the `res()` call. One such place is the `notFoundByDefault` function in `mock_server.js@38`. So, instead of treating any unhandled requests as 404, MSW now _performs them as-is_ because you haven't returned any mocked response. I highly recommend fixing this. I've fixed this locally but it hasn't affected the tests (seemingly). 

I've checked the list of handlers in one of the failing tests via `server.printHandlers()`, and I can see that those GraphQL operations are listed there:

```
[graphql] query GetProject (origin: *)
  Declaration: /gitlab-vscode-extension-renovate-msw-0.x/test/integration/test_infrastructure/mock_server.js:59:13


[rest] GET https://test.gitlab.com/api/v4/version
  Declaration: /gitlab-vscode-extension-renovate-msw-0.x/test/integration/test_infrastructure/mock_server.js:9:8


[rest] GET https://test.gitlab.com/api/v4/user
  Declaration: /gitlab-vscode-extension-renovate-msw-0.x/test/integration/test_infrastructure/mock_server.js:9:8


[graphql] query GetIssueDiscussions (origin: *)
  Declaration: /gitlab-vscode-extension-renovate-msw-0.x/test/integration/webview.test.js:29:15


[graphql] mutation CreateNote (origin: *)
  Declaration: /gitlab-vscode-extension-renovate-msw-0.x/test/integration/webview.test.js:34:15


[rest] GET https://test.gitlab.com/api/v4/projects/278964/issues/219925/resource_label_events
  Declaration: /gitlab-vscode-extension-renovate-msw-0.x/test/integration/test_infrastructure/mock_server.js:9:8


[rest] GET /.*/
  Declaration: /gitlab-vscode-extension-renovate-msw-0.x/node_modules/msw/lib/index.js:536:36
```

Yet, neither of those handlers matched or returned any mocked responses for the unhandled behavior to trigger. 

I can also see this error:

```
API call https://test.gitlab.com/api/v4/projects/278964/issues/219925/resource_label_events?sort=asc doesn't have a query handler.
```

I don't know if it's connected but it looks something cannot be fetched. 

## So, what changed in 0.42?

We've migrated to the next version of Interceptors—the library MSW uses to intercept requests in Node.js (and sometimes in the browser). With this migration, the interception in Node is now event-based, which shouldn't affect the consumers but may introduce some additional asynchronicity. 



## Suggestions

- Make sure to always return `res()` if you call it. 
- Keep in mind that since [0.40.0](https://github.com/mswjs/msw/releases/tag/v0.40.0) to bypass a request (perform it as-is) you need to use `req.passthrough()` (previously could do early return or `return undefined`).
- Try to see if there aren't any race conditions between your `server` being created and the test being run. 

The biggest issue for me is that I cannot run MSW or Interceptors in debug mode. It simply doesn't apply to your tests. I suspect there's some additional testing infrastructure that prevents me from doing what I want to do. But since you're more familiar with it, I recommend running your tests with the `DEBUG=http*` variable:

```sh
DEBUG=http* your-test-command
```

This will run Interceptors in debug mode, printing additional info about how interceptors are applied, what requests they receive, and what response they produce. It will also include info on whether MSW returned any mocked response or not. I highly recommend this as a debugging step to see what may be wrong. 

Here's an example of me using `DEBUG=http*` in your standalone reproduction repository (which doesn't have the issue):

```sh
  http:request GET https://test.gitlab.com/version emitting the "request" event for 1 listener(s)... +0ms
  http:request GET https://test.gitlab.com/version event:socket +4ms
  http:request GET https://test.gitlab.com/version event.respondWith called with: {
  status: 200,
  statusText: 'OK',
  headers: { 'x-powered-by': 'msw', 'content-type': 'text/plain' },
  body: 'abc'
} +1ms
  http:request GET https://test.gitlab.com/version the listeners promise awaited! +1ms
  http:request GET https://test.gitlab.com/version received mocked response: {
  status: 200,
  statusText: 'OK',
  headers: { 'x-powered-by': 'msw', 'content-type': 'text/plain' },
  body: 'abc'
} +0ms
```

I can see the intercepted request, that it awaited all the listeners, and that it has received a mocked response from MSW. Then, in the conclusion I can see the response that's sent:

```sh
  http:request GET https://test.gitlab.com/version 200 OK abc (MOCKED) +1ms
```

I'm sorry I can't be of more help. If you get a chance to recreate this issue, please post the repo here, I'll look into it. But until then I'm forced to close the issue.

**Closed as completed by kettanaito** 2022-06-09 12:47 UTC
Labels: bug, scope:node, needs:triage
