### ISSUE TITLE
Headers created before `server.listen()` are not being considered after changed with `headers.set()` or `headers.append()`

### ISSUE THREAD

**Issue by diego-aquino** [kettanaito/msw#2297] opened 2024-09-29 16:33 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.17.0

### Reproduction repository

https://github.com/diego-aquino/msw-headers-init-repro-with-vitest

### Reproduction steps

1. Clone the reproduction repository
2. `npm install`
3. `npm run test`

### Current behavior

The `README.md` of the reproduction repository contains a more detailed explanation. Here's a summary:

I created two identical test suites, except for the imported MSW version:

- `passing-on-v2.4.3.test.ts` - This suite is using `msw@2.4.3` and passes.
- `failing-on-v2.4.9.test.ts` - This suite is using `msw@2.4.9` and fails.

Before starting the MSW server, each suite creates a `Headers` instance with initial values, appends a new header and checks if the initial values are preserved and the instance contains the correct values.

After starting the server with `server.listen()`, the suites append yet another header to the instance and re-run the checks. With `msw@2.4.3`, the existing values are preserved and the new header is appended. However, the current headers are lost with `msw@2.4.9` when used in a `Request` or `fetch` call. The only kept header is the one appended _after_ starting the server, as if the instance was empty before.

The problem does not appear to occur when using the headers directly, because only the last expect reading the headers from a `Request` fails.

### Expected behavior

For headers created before `server.listen()`, `Request` and `fetch` should consider their previous values after changed with `set` or `append`. This was the behavior with `msw@2.4.3` and appears to have changed in `msw@2.4.4` and later.

Let me know if there is anything unclear I could clarify!

**Comment by jeanpaze** [comment] 2024-09-30 10:12
I can confirm, this is also happening to me.

Previously this test was working:

`expect(response.headers.get("Content-Type")).toBe("text/html");`

But started to fail with version `2.4.4` and above:
```
- Expected: 
"text/html"

+ Received: 
null
```

**Comment by plavski** [comment] 2024-10-03 12:49
Any potential movement here? This is holding off our upgrade as we have a lot of tests designed this way.

**Comment by cythrawll** [comment] 2024-10-11 06:18
I just got bit by this bug. couldn't figure why my remix server was serving everything as plain/text for a few hours now when MSW mocks were turned on, only to find out my express server stopped sending `Content-Type` headers at all.

worked around this bug by loading my mock setupServer script with npm command instead of inline in my express server so now doing something like in my package.json:

```js
scripts: {
  dev: 'tsx -r ./mocks/index.ts server.ts'
}
```

**Comment by kettanaito** [comment] 2024-11-10 14:28
## Update

#2269 and #2278 have been fixed and look suspiciously similar to what you are describing. I recommend updating to the latest of `msw` to verify. 

@diego-aquino, I confirm that your reproduction repo has the tests passing on `msw@latest`:

```
 ✓ tests/failing-on-2.4.9.test.ts (1)
   ✓ preserves init values in headers created before the server was started
```

Just make sure to remove the pervious `msw` version because it looks like npm is resolving `@mswjs/interceptors` from the 2.4.3, which is an extremely old version that doesn't contain the fix.

**Closed as completed by kettanaito** 2024-11-10 14:28 UTC
Labels: bug, scope:node, needs:triage
