### ISSUE TITLE
Native node.js fetch doesn't abort when an msw server is running

### ISSUE THREAD

**Issue by n-e** [kettanaito/msw#1701] opened 2023-08-18 12:26 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v20.5.0 and v18.17.1

### Reproduction repository

https://github.com/n-e/msw-bug-repro

### Reproduction steps

Run `node index.js` in the provided repo

### Current behavior

The fetch call returns after 2 seconds.

### Expected behavior

The fetch call should fail with a timeout, since : 
- it has `{ signal: AbortSignal.timeout(1) }` as an argument
- when `server.listen()` is commented, it fails

**Comment by kettanaito** [comment] 2023-08-26 09:55
Hi, @n-e. Thanks for reporting this. It's a known issue and we are addressing it in https://github.com/mswjs/interceptors/pull/394 (discussion https://github.com/mswjs/msw/discussions/1646). We have to forward the custom `AbortController` to the internal representation of the request to respect user-based abort signals. While this sounds relatively straightforward, there's more to it than it seems. I need to dive deeper into this and make sure we get this fix right.

**Comment by Lukas-Kullmann** [comment] 2023-10-11 13:12
Hey @kettanaito the related mswjs/interceptors PR has been merged for quite some time now, but it still does not work with the current version of msw.
I guess the problem is that the current msw version uses an older version of @mswjs/interceptors (0.17) than the version that this fix was implemented for (0.24). However, the current interceptor version is not compatible with the current version of msw.
Is there a chance that this will be backported to interceptors v0.17?

**Comment by kettanaito** [comment] 2023-11-14 09:37
Hi, @Lukas-Kullmann. Since 2.0, MSW runs the latest version of Interceptors, which includes the fix for this issue. There are no plans to backport this fix to the older versions of Interceptors because it works on a fundamentally different architecture and requires time that I, sadly, don't have at the moment. 

Please upgrade to MSW 2.0 and this issue will be gone. We forward request abort events correctly.

**Closed as completed by kettanaito** 2023-11-14 09:37 UTC
Labels: bug, scope:node, needs:triage
