### ISSUE TITLE
CodeSandbox template recommended for issues doesn't work

### ISSUE THREAD

**Issue by lgenzelis** [kettanaito/msw#1948] opened 2024-01-03 14:30 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Reproduction repository

https://codesandbox.io/s/msw-react-xx1c8

### Reproduction steps

When opening a new issue, we see 

> Reproduction repository
> A link to the repository where your issue can be reproduced. You can clone one of [our examples](https://github.com/mswjs/examples/tree/master/examples) or [our CodeSandbox template](https://codesandbox.io/s/msw-react-xx1c8) to create a reproduction repository much faster. Issues without a reproduction repository will be closed.

However, if we go to the [CodeSandbox template](https://codesandbox.io/s/msw-react-xx1c8), we see 

<img width="1917" alt="Screenshot 2024-01-03 at 11 29 12 AM" src="https://github.com/mswjs/msw/assets/4582440/9ea5cdbc-f8b5-4309-b334-be743c79cdac">

### Current behavior

-

### Expected behavior

Codesando

**Comment by kettanaito** [comment] 2024-01-28 12:09
Duplicate of #1588.

**Closed as completed by kettanaito** 2024-01-28 12:09 UTC
Labels: bug, scope:browser, needs:triage
