### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by jfzhou90** [kettanaito/msw#1940] opened 2023-12-21 21:06 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

N/A

### Reproduction steps

`import React from 'react';
import ReactDOM from 'react-dom/client';

import App from './App';

const enableMockServer = true;

const init = async () => {
  if (import.meta.env.MODE !== 'development' || !enableMockServer) {
    return null;
  }

  const { worker } = await import('common/unitTest/browser');

  return worker.start({ onUnhandledRequest: 'bypass' });
};

init().then(() =>
  ReactDOM.createRoot(document.getElementById('root')!).render(
    <React.StrictMode>
      <App />
    </React.StrictMode>
  )
);
`

I'm using ViteJS React SWC Typescript.

### Current behavior

Whenever strict mode is on, this error shows up
![CleanShot 2023-12-21 at 16 03 20](https://github.com/mswjs/msw/assets/26238935/0ee88089-f1a0-43e9-900a-932ba884a4bb)

and sometimes the mock service would not intercept the request, and bypassed to the real server

### Expected behavior

The mock should be more reliable and not leak into the actual server.

**Comment by janwidmer** [comment] 2024-01-01 10:30
I experience the same problem, we use msw within an angular application with several handlers. The Warning appears consistently in the browser console right after starting the application:
<img width="725" alt="image" src="https://github.com/mswjs/msw/assets/3381820/d713ada8-823d-4af3-ae4c-6a4f29d71ae8">

**Comment by mattcosta7** [comment] 2024-01-02 14:35
There's no significant issue here, and you should be safe to ignore this message.  Closing as a duplicate of https://github.com/mswjs/msw/issues/1911, which has a bit more context

unrelated to strict mode, which doesn't impact this on the msw side, but is just due to the number of 'request clones' occuring for specific requests

**Closed as not planned by mattcosta7** 2024-01-02 14:35 UTC
Labels: bug, scope:browser, needs:triage
