### ISSUE TITLE
[msw@next] Cannot import `msw/browser` in Next.js 13

### ISSUE THREAD

**Issue by wonu** [kettanaito/msw#1618] opened 2023-05-12 19:46 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Reproduction repository

https://codesandbox.io/p/sandbox/green-haze-xucwmi?file=%2Fapp%2Fpage.tsx%3A14%2C33

### Reproduction steps

npm run dev

(The reproduction repository was forked from [the issue template](https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template-app-dir) of Next.js.)

### Current behavior

In Next.js 13, importing `msw/browser` throws an error:
```
Module not found: Package path ./lib/browser/index is not exported from package ...\node_modules\msw (see exports field in ...\node_modules\msw\package.json)
```

I think the added conditional export `{"./browser" : {"node": null}}` in `package.json` is the cause: https://github.com/mswjs/msw/blob/v0.0.0-fetch.rc-14/package.json#L15C1-L16

I imported it in `useEffect()` with `import()`, but I don't know how it is considered as Node.js environment.
On the other hand, the exact same `useEffect()` code works fine in Remix.

How can I use it in Next.js?

### Expected behavior

I want to import `msw/browser` in Next.js 13

**Comment by kettanaito** [comment] 2023-05-13 10:31
Hey, @wonu. Thanks for reporting this. 

I believe the conditional export is correct—you must not import `msw/browser` in Node.js. The problem is that it's not always obvious that the code you modify will run in Node.js. 

As you are trying to achieve what looks like a Next 13 integration, I am hesitant to suggest you any steps to solve this. I am still thinking on the best way to integrate MSW into the new Next but I wouldn't generally advise doing that in a `useEffect()`. 

> As a side note, don't forget to `await worker.start()`, is an async action. 

I will close this because I cannot consider it an issue given we don't promise this integration at the moment. I will try sharing my progress on the Next 13 integration in the [Examples repo](https://github.com/mswjs/examples-new) when I have time. Maybe we could collaborate on that!

**Closed as completed by kettanaito** 2023-05-13 10:31 UTC
Labels: bug, scope:browser, needs:triage
