### ISSUE TITLE
Axios upload (onUploadProgress) event is not supported

### ISSUE THREAD

**Issue by pkaufi** [kettanaito/msw#1131] opened 2022-02-28 08:33 UTC
## Describe the bug
The error was introduced with `msw: 0.38.0` where `@mswjs/interceptors: 13` was added. More specifically here: https://github.com/mswjs/interceptors/pull/193. 
We have a repository that uses `axios`. It looks like `axios` is doing the following check
```
// Not all browsers support upload events
if (typeof config.onUploadProgress === 'function' && request.upload) {
  request.upload.addEventListener('progress', config.onUploadProgress);
}
```
In some of our tests, we set `onUploadProgress` to test some upload behaviour. With the above mentioned change, `request.upload` is now `true`, whereas it was `false` before. It being `true` now breaks with the error message  `TypeError: request.upload.addEventListener is not a function`.

## Environment

- `msw: 0.38.0`
- `nodejs: 14.17.1`
- `yarn: 1.22.15`

## To Reproduce
1. Go to https://github.com/pkaufi/msw-with-jest
2. Run `yarn && yarn test`
3. See the test fail with `TypeError: request.upload.addEventListener is not a function`

## Expected behavior
No error.

**Comment by kettanaito** [comment] 2022-03-06 17:15
Hey, @pkaufi. Thanks for reporting this. Also big thanks for the reproduction repository!

XHR upload is generally not supported by MSW as of yet. We've set the `upload` property on XHR to an empty object to grant some sort of compatibility with tools that access it. Looks like `upload` also extends an event emitter. 

The upload support is tracked here: https://github.com/mswjs/interceptors/issues/187. I'm against any more partial solutions at this point and want this to be solved fundamentally by bringing upload support to the MSW toolchain.

**Comment by pkaufi** [comment] 2022-03-08 09:12
Hey @kettanaito, thank you for your response. I understand your reasoning and will therefore either wait before upgrading to the latest version or just disable/rewrite those tests for now.

**Comment by kettanaito** [comment] 2022-05-02 10:50
I'm going to close this issue since the upload progress is tracked in https://github.com/mswjs/interceptors/issues/187.

**Closed as completed by kettanaito** 2022-05-02 10:50 UTC
Labels: feature
