### ISSUE TITLE
Next js 'with-msw' installation breaks when enabling React 18 + experimental concurrency features.

### ISSUE THREAD

**Issue by laurencefass** [kettanaito/msw#1054] opened 2022-01-11 16:11 UTC
## Describe the bug
msw is not compatible with Next JS + React 18 concurrent experimental mode. The site breaks when i enable it and works again when I disable it. I believe it may be the setupServer function that is failing. 

## Environment

msw: 0.36.4
next js: 12.07
node.js v16.13.1
o/s: Debian host/Docker/Alpine 3.14
deployment: Debian host/Docker/Alpine container

> Please also provide your browser version.
Chrome Version 96.0.4664.110 (Official Build) (64-bit)

## To Reproduce
I wanted to test out the new React 18 concurrency and server component features using a mock API with msw . I have installed the msw template from [here](https://github.com/vercel/next.js/tree/canary/examples/with-msw) and all works fine with React 17 and upgraded to React 18 according to instructions [here](https://nextjs.org/docs/advanced-features/react-18) 

Prequisite tests: I installed and tested vanilla Next js upgraded to react and react-dom 18 with experimental concurrency configured in next.config.js and it works fine. There appears to be a problem arising between concurrency features and the official next js msw template.

i.e. i used yarn add next@latest react@rc react-dom@rc

after upgrade i have package.json

```
{
  "private": true,
  "scripts": {
    "dev": "next dev -p 3201",
    "build": "next build",
    "start": "next start -p 3201"
  },
  "dependencies": {
    "msw": "^0.29.0",
    "nanoid": "^3.1.30",
    "next": "^12.0.7",
    "random-words": "^1.1.1",
    "react": "^18.0.0-rc.0",
    "react-dom": "^18.0.0-rc.0"
  },
  "msw": {
    "workerDirectory": "public"
  }
}
```

msw works fine and the github demo works perfectly until I enable concurrent features in next.config.js

```
// next.config.js
module.exports = {
    experimental: {
      concurrentFeatures: true,
    },
}
```

with concurrentFeatures enabled the index.ts doesnt load and I can see an error log on the server:

```
8|next-nex | > next dev -p 3201
8|next-nex |
8|next-nex | ready - started server on 0.0.0.0:3201, url: http://localhost:3201
8|next-nex | info  - Loaded env from /app/next/next18/.env.development
8|next-nex | info  - Using the createRoot API for React
8|next-nex | wait  - compiling...
8|next-nex | event - compiled client and server successfully in 1800 ms (189 modules)

8|next-next18  | warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
8|next-next18  | wait  - compiling / (client and server)...
8|next-next18  | wait  - compiling...
8|next-next18  | event - compiled client and server successfully in 887 ms (413 modules)
8|next-next18  | error - TypeError: Cannot read properties of undefined (reading 'indexOf')
8|next-next18  | wait  - compiling /_error (client and server)...
8|next-next18  | wait  - compiling...
8|next-next18  | event - compiled client and server successfully in 408 ms (414 modules)
```

If I disable experimental concurrent features in next.config.js msw works fine again.

## Expected behavior
msw compatbility with Next js as it is a major React framework that already offers concurrent support and therefore  an opportunity for testing with React 18 features.

## Screenshots
Browser screenshots not applicable the page just fails to load. Clicking page reload in the browser 5 times results in a repeat of the error which I think stems from a failure of 
```
8|next-next18  | error - TypeError: Cannot read properties of undefined (reading 'indexOf')
8|next-next18  | error - TypeError: Cannot read properties of undefined (reading 'indexOf')
8|next-next18  | error - TypeError: Cannot read properties of undefined (reading 'indexOf')
8|next-next18  | error - TypeError: Cannot read properties of undefined (reading 'indexOf')
8|next-next18  | error - TypeError: Cannot read properties of undefined (reading 'indexOf')
```

**Comment by kettanaito** [comment] 2022-01-11 17:17
Hey, @laurencefass. Thanks for reporting this.

This looks like the same issue you've reported in #1053. Did re-initializing the project not help in the end? 

I'm afraid if the issue occurs only with React 18 there isn't much I can help with. We don't have the bandwidth to support experimental releases of various frameworks like React or Next. Supporting experimental things always implies time overhead, as those frameworks may change significantly, rendering our fixes obsolete. But we do guarantee operability with the public versions. 

If you can reproduce this issue with the current stable version of React/Next, then please let us know. If not, I'd close this issue until React 18 is released and globally available. Thanks for understanding.

**Closed as completed by kettanaito** 2022-01-11 17:17 UTC
Labels: bug

**Comment by laurencefass** [comment] 2022-01-11 17:24
Confirming again the issue only occurs with React 18 optionally enabled in next js. No issues with 17 and below. Thanks.

**Comment by kettanaito** [comment] 2022-01-11 17:26
Thanks for the confirmation! 
Let's take a look at this once those versions become stable.
