### ISSUE TITLE
"Cannot find module 'msw/node'" in Jest JSDOM environment

### ISSUE THREAD

**Issue by textbook** [kettanaito/msw#1786] opened 2023-10-23 12:28 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v18.18.2

### Reproduction repository

https://github.com/textbook/msw2-mre

### Reproduction steps

`npm ci && npm test`

### Current behavior

Error message

> Cannot find module 'msw/node' from 'path/to/file'

```bash
$ npm test

> msw2@0.1.0 test
> jest

 FAIL  ./index.test.js
  ● Test suite failed to run

    Cannot find module 'msw/node' from 'index.test.js'

      1 | const { http, HttpResponse } = require("msw");
    > 2 | const { setupServer } = require("msw/node");
        |                         ^
      3 |
      4 | const server = setupServer();
      5 |

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.require (index.test.js:2:25)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.961 s
Ran all test suites.
Error: Process completed with exit code 1.
```

🔴 [Failing Actions run](https://github.com/textbook/msw2-mre/actions/runs/6615230682)

### Expected behavior

The test should pass, as it does if you switch to the Node environment by updating `jest.config.js` as follows:

```diff
diff --git a/jest.config.js b/jest.config.js
index f343a5c..4e07134 100644
--- a/jest.config.js
+++ b/jest.config.js
@@ -13,5 +13,5 @@ module.exports = {
                ReadableStream,
                TextEncoder,
        },
-       testEnvironment: "jsdom",
+       testEnvironment: "node",
 };

```

Outcome:

```bash
$  npm test

> msw2@0.1.0 test
> jest

 PASS  ./index.test.js
  ✓ works (10 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.203 s
Ran all test suites.
```

**Comment by textbook** [comment] 2023-10-23 12:29
- It's possibly related to #1705, but it's a slightly different error message and I'm not using Next.js.
- I also tried using `setupWorker` from `msw/browser`, in case the JSDOM environment was sufficiently browser-y for that to work, but got ```Invariant Violation: [MSW] Failed to execute `setupWorker` in a non-browser environment. Consider using `setupServer` for Node.js environment instead.```

**Comment by csantos-nydig** [comment] 2023-10-23 13:52
I got a similar error but running ESLINT

```
error: Resolve error: Package subpath './browser' is not defined by "exports" in /Users/cesar.santos/app/node_modules/msw/package.json
```

```
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:612:7)
    at resolveExports (node:internal/modules/cjs/loader:522:36)
    at Module._findPath (node:internal/modules/cjs/loader:562:31)
    at findModulePath (/Users/cesar.santos/app/node_modules/eslint-import-resolver-alias/index.js:99:27)
    at exports.resolve (/Users/cesar.santos/app/node_modules/eslint-import-resolver-alias/index.js:75:10)
    at v2 (/Users/cesar.santos/app/node_modules/eslint-module-utils/resolve.js:116:23)
    at withResolver (/Users/cesar.santos/app/node_modules/eslint-module-utils/resolve.js:121:14)
    at fullResolve (/Users/cesar.santos/app/node_modules/eslint-module-utils/resolve.js:138:22)
    at relative (/Users/cesar.santos/app/node_modules/eslint-module-utils/resolve.js:83:10)
    at resolve (/Users/cesar.santos/app/node_modules/eslint-module-utils/resolve.js:219:12)
    at isImportingSelf (/Users/cesar.santos/app/node_modules/eslint-plugin-import/lib/rules/no-self-import.js:14:70)
    at commonjs (/Users/cesar.santos/app/node_modules/eslint-plugin-import/lib/rules/no-self-import.js:35:9)
    at checkSourceValue (/Users/cesar.santos/app/node_modules/eslint-module-utils/moduleVisitor.js:29:5)
    at checkCommon (/Users/cesar.santos/app/node_modules/eslint-module-utils/moduleVisitor.js:67:5)
    at visitors.CallExpression (/Users/cesar.santos/app/node_modules/eslint-module-utils/moduleVisitor.js:105:29)
    at ruleErrorHandler (/Users/cesar.santos/app/node_modules/eslint/lib/linter/linter.js:1115:28)
    ...
```

I'm not sure why this "node: null" is needed 👇 
https://github.com/mswjs/msw/blob/a54138a62a7e89bd5f768d369e6b5bc4c46686ae/package.json#L16-L17

but removing it fixes my issue above

**Comment by jcnix** [comment] 2023-10-23 21:40
This is what resolved it for me from the examples repository.  I don't pretend to know what this does, but it works.

https://github.com/mswjs/examples/blob/main/examples/with-jest/jest.config.ts#L20

**Comment by arturmiglio** [comment] 2023-10-24 01:32
> This is what resolved it for me from the examples repository. I don't pretend to know what this does, but it works.
> 
> https://github.com/mswjs/examples/blob/main/examples/with-jest/jest.config.ts#L20

For me, this works only partially. As it breaks other imports.

**Comment by PaulWild** [comment] 2023-10-26 09:50
We are unfortunately  seeing the same issue when upgrading to v2. This is blocking us from moving to the new version. It is a Nextjs project and works without issue in v1

**Comment by okhomenko** [comment] 2023-10-26 20:47
cc @kettanaito

**Comment by DercilioFontes** [comment] 2023-10-26 21:37
I have the same issue using `react`, `vite` and `vitest`.

```
"react": "^18.2.0",
"react-dom": "^18.2.0",
"@testing-library/jest-dom": "^6.1.4",
"@testing-library/react": "^14.0.0",
"vite": "^4.5.0",
"vitest": "^0.34.6",
```

System:
   NodeJS : v18.18.2
   npm    : 9.8.1
   OS     : macOS 13.5.2

**Comment by kettanaito** [comment] 2023-10-27 09:02
## Why does this error happen?

Because JSDOM forces the `browser` export condition. In other words, JSDOM says "if a third-party package exports a `browser` field, use that." That's the default and a rather dangerous default at that. Why? Because JSDOM _still runs in Node.js_. More to that, JSDOM cannot have 100% browser compatibility by design, so forcing the `browser` export condition will subject your tests to failures more than necessary when working with packages that ship different code for different environments, like MSW does. 

The `msw/node` import must never happen in the browser code. Thus, MSW has the following export condition to ensure that on the bundler level: 

https://github.com/mswjs/msw/blob/1d1fbca6a39b0d89c7e18bc50cab73ddac7ea5f0/package.json#L23-L24

The same is true for the `msw/browser` import in Node.js. This is the right setup to achieve publishing to multiple environments at once. The problem is not the package but how your test environment is configured. Export conditions is a relatively new feature is Node.js, and some tools are either lacking behind, don't understand it entirely, or, like JSDOM, assume dangerous defaults that put the users in confusing situations. 

## How to solve this?

Opt out of the `browser` export condition by adding this to your `jest.config.js`:

```js
// jest.config.js 
module.exports = {
  testEnvironmentOptions: {
    customExportConditions: [''],
  }
}
```

This will force JSDOM to use the `node` (or `default`) export condition, which is the correct behavior. 

If you encounter other import-related issued after this change, they aren't related and have to be addressed separately. Adding this recommendation to the migration guide as well so everyone could follow.

**Closed as completed by kettanaito** 2023-10-27 09:02 UTC
Labels: bug, scope:node, needs:triage

**Comment by textbook** [comment] 2023-10-27 09:51
Confirmed, now 🟢 [passes](https://github.com/textbook/msw2-mre/actions/runs/6665627759) in both `testEnvironment`s - thanks!

**Comment by DercilioFontes** [comment] 2023-10-27 13:01
> I have the same issue using `react`, `vite` and `vitest`.
> 
> ```
> "react": "^18.2.0",
> "react-dom": "^18.2.0",
> "@testing-library/jest-dom": "^6.1.4",
> "@testing-library/react": "^14.0.0",
> "vite": "^4.5.0",
> "vitest": "^0.34.6",
> ```
> 
> System: NodeJS : v18.18.2 npm : 9.8.1 OS : macOS 13.5.2

I see that it is working for `vitest` with this change in the `vite` config:
```typescript
{
// ...
 define: {
      'process.env.NODE_ENV': `"${mode}"`,
    },
    build: {
      target: ['ES2022'],
      outDir: 'build',
    },
    server: {
      open: mode === 'development',  // <-- here (it was true before). It will be 'test' and will not open the server
      port: 8101,
    },
    // https://vitest.dev/config/
    test: {
      globals: true,
      environment: 'jsdom',
      setupFiles: 'src/setupTests.ts',
    },
// ...
}
 ```

**Comment by joshkel** [comment] 2023-10-30 22:07
Disabling Jest's `customExportConditions` everywhere seemed somewhat drastic to me; I was hoping to change just the interaction between Jest and MSW, instead of changing everything within Jest to make MSW happy. (And, in a brief test, I ran into problems with other packages not working correctly when I cleared `customExportConditions`.)

Instead, I'm using a custom Jest resolver to modify MSW's imports.

**Please note:** This is a hack. It's deliberately doing something not intended by the MSW project. Subsequent MSW updates may break it. If you do this and it causes problems, please do not report any resulting issues to this project.

To do this: In the Jest config, define your resolver:

```
  resolver: `${__dirname}/config/jest/resolver.js`,
```

And create it with the following contents:

```js
// Based on https://github.com/microsoft/accessibility-insights-web/pull/5421#issuecomment-1109168149
module.exports = (path, options) => {
  // Call the defaultResolver, so we leverage its cache, error handling, etc.
  return options.defaultResolver(path, {
    ...options,
    // Use packageFilter to process parsed `package.json` before the resolution
    // (see https://www.npmjs.com/package/resolve#resolveid-opts-cb)
    packageFilter: (pkg) => {
      if (pkg.name === 'msw') {
        delete pkg.exports['./node'].browser;
      }
      if (pkg.name === '@mswjs/interceptors') {
        delete pkg.exports;
      }

      return pkg;
    },
  });
};
```

**Comment by joshkel** [comment] 2023-10-31 18:08
Here's an improved version of my [custom Jest `resolver`](https://github.com/mswjs/msw/issues/1786#issuecomment-1786122056) that replaces `customExportConditions` just for MSW, while leaving Jest's `browser` export for other code that expects it. This allows tests of code that's intended to run in the browser to continue to use the browser versions of other packages, while following MSW's expectation and recommendation of using MSW's Node code within tests.

```js
module.exports = (path, options) => {
  // Jest + jsdom acts like a browser (i.e., it looks for "browser" imports
  // under pkg.exports), but msw knows that you're operating in a Node
  // environment:
  //
  // https://github.com/mswjs/msw/issues/1786#issuecomment-1782559851
  //
  // The MSW project's recommended workaround is to disable Jest's
  // customExportConditions completely, so no packages use their browser's
  // versions.  We'll instead clear export conditions only for MSW.
  if (/^(msw|@mswjs\/interceptors)(\/|$)/.test(path)) {
    return options.defaultResolver(path, { ...options, conditions: [] });
  }

  return options.defaultResolver(path, options);
};
```

If this works for others, it may be worth adding as an option in [the docs](https://mswjs.io/docs/migrations/1.x-to-2.x#cannot-find-module-mswnode-jsdom).

**Comment by kettanaito** [comment] 2023-11-01 19:41
> I was hoping to change just the interaction between Jest and MSW, instead of changing everything within Jest to make MSW happy.

JSDOM is broken export conditions-wise, I believe I explained it [at length](https://github.com/mswjs/msw/issues/1786#issuecomment-1782559851). It's not about making MSW happy, it's about resolving third-party modules using the `node` export _while running in Node.js_. This is how module resolution is supposed to work, and by using old tools you are not getting the modern JavaScript. If you don't believe me, try Vitest. It works with the correct module resolution out of the box. 

@joshkel, your custom resolver implementation looks interesting. I will leave it up to the people to decide which approach works best for them, but may I please stress this one last and final time: **You need all this because you are using an OLD testing framework.** Whether you decide to ignore the `browser` export condition in Node, which is what you should be doing, to begin with, or introduce a custom `resolver` for Jest—nothing of this has anything to do with MSW. Hope we get this straight in the discussions to come. Thanks.

**Comment by cleysonsilvame** [comment] 2023-11-02 09:04
> ## Why does this error happen?
> Because JSDOM forces the `browser` export condition. In other words, JSDOM says "if a third-party package exports a `browser` field, use that." That's the default and a rather dangerous default at that. Why? Because JSDOM _still runs in Node.js_. More to that, JSDOM cannot have 100% browser compatibility by design, so forcing the `browser` export condition will subject your tests to failures more than necessary when working with packages that ship different code for different environments, like MSW does.
> 
> The `msw/node` import must never happen in the browser code. Thus, MSW has the following export condition to ensure that on the bundler level:
> 
> https://github.com/mswjs/msw/blob/1d1fbca6a39b0d89c7e18bc50cab73ddac7ea5f0/package.json#L23-L24
> 
> The same is true for the `msw/browser` import in Node.js. This is the right setup to achieve publishing to multiple environments at once. The problem is not the package but how your test environment is configured. Export conditions is a relatively new feature is Node.js, and some tools are either lacking behind, don't understand it entirely, or, like JSDOM, assume dangerous defaults that put the users in confusing situations.
> 
> ## How to solve this?
> Opt out of the `browser` export condition by adding this to your `jest.config.js`:
> 
> ```js
> // jest.config.js 
> module.exports = {
>   testEnvironmentOptions: {
>     customExportConditions: [''],
>   }
> }
> ```
> 
> This will force JSDOM to use the `node` (or `default`) export condition, which is the correct behavior.
> 
> If you encounter other import-related issued after this change, they aren't related and have to be addressed separately. Adding this recommendation to the migration guide as well so everyone could follow.

I have a similar situation

Inside the test environment (using `vitest`), I get the same error, because with `./browser`.

If I follow the instruction to remove the conditional `node`, or put an empty string in the array, I end up breaking other tests that need the conditional `node`

Does anyone have any suggestions?

**Comment by DercilioFontes** [comment] 2023-11-02 11:42
> > ## Why does this error happen?
> > Because JSDOM forces the `browser` export condition. In other words, JSDOM says "if a third-party package exports a `browser` field, use that." That's the default and a rather dangerous default at that. Why? Because JSDOM _still runs in Node.js_. More to that, JSDOM cannot have 100% browser compatibility by design, so forcing the `browser` export condition will subject your tests to failures more than necessary when working with packages that ship different code for different environments, like MSW does.
> > The `msw/node` import must never happen in the browser code. Thus, MSW has the following export condition to ensure that on the bundler level:
> > https://github.com/mswjs/msw/blob/1d1fbca6a39b0d89c7e18bc50cab73ddac7ea5f0/package.json#L23-L24
> > 
> > The same is true for the `msw/browser` import in Node.js. This is the right setup to achieve publishing to multiple environments at once. The problem is not the package but how your test environment is configured. Export conditions is a relatively new feature is Node.js, and some tools are either lacking behind, don't understand it entirely, or, like JSDOM, assume dangerous defaults that put the users in confusing situations.
> > ## How to solve this?
> > Opt out of the `browser` export condition by adding this to your `jest.config.js`:
> > ```js
> > // jest.config.js 
> > module.exports = {
> >   testEnvironmentOptions: {
> >     customExportConditions: [''],
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will force JSDOM to use the `node` (or `default`) export condition, which is the correct behavior.
> > If you encounter other import-related issued after this change, they aren't related and have to be addressed separately. Adding this recommendation to the migration guide as well so everyone could follow.
> 
> I have a similar situation
> 
> Inside the test environment (using `vitest`), I get the same error, because with `./browser`.
> 
> If I follow the instruction to remove the conditional `node`, or put an empty string in the array, I end up breaking other tests that need the conditional `node`
> 
> Does anyone have any suggestions?

I put a vitest config example here (https://github.com/mswjs/msw/issues/1786#issuecomment-1782879435). It is working for me. No need to do anything else.

**Comment by kettanaito** [comment] 2023-11-02 13:53
Please refer to the usage examples with Vitest that feature both ESM and CJS tests, all functional with MSW v2.0:

- [Vitest](https://github.com/mswjs/examples/tree/main/examples/with-vitest)
- [Vitest CJS](https://github.com/mswjs/examples/tree/main/examples/with-vitest-cjs)

I've also just migrated the entire internal test suite of MSW to Vitest yesterday without any issues. You don't need to configure JSDOM in any way for Vitest+MSW to work.

**Comment by joshkel** [comment] 2023-11-02 14:11
Thanks for the reply, @kettanaito (and for your patience).

If I'm understanding correctly, it's not a matter of Jest being old or not supporting modern module resolution. (Jest fully supports modern modules and module resolution, as far as I know - somewhat held back by [issues in Node.js itself](https://github.com/jestjs/jest/issues/11956).) Instead, it's a legitimate trade-off:

* There are advantages to emulating the browser as closely as possible when testing browser code. (It's the same testing philosophy as [Kent Dodds](https://twitter.com/kentcdodds/status/977018512689455106), I guess.)
* There are advantages to being honest and accepting that the code runs in Node.js. The resulting code can be much simpler and can leverage pre-existing functionality (although that functionality may not behave the same as it does in the browser).

Jest and jsdom seem to default to the first approach. jsdom [won't use implementations](https://www.github.com/jsdom/jsdom/issues/1724#issuecomment-285971986) if they're not W3C-spec-compliant, and Jest uses the VM API (I think) to exclude Node.js globals (so code under test won't mistakenly reference them), and Jest decides to emulate the browser as closely as possible when using jsdom, including honoring the `"browser"` export conditions of Node modules. (And, since Jest's jsdom environment doesn't expose Node.js globals, some packages _need_ to have their `"browser"` export conditions honored, so they'll reference browser globals rather than Node.)

Vitest takes the second approach (e.g., it exposes Buffer because ["TODO a lot of dependencies use it"](https://github.com/vitest-dev/vitest/blob/3397fdc45cc0f57df4f7afe08e472a9c5ff360b9/packages/vitest/src/integrations/env/jsdom.ts#L69)) - but that means I can have production browser-side code that mistakenly references Buffer and passes tests and fails at runtime. MSW 2 picks the second approach (for [reasons that you explain in depth](https://mswjs.io/blog/introducing-msw-2.0#the-essence)), and I'm certain those are the correct tradeoffs for MSW - but now I have test failures because `new FormData(form)` no longer works. (This is not a complaint and not your problem.)

It wouldn't surprise me if Jest's tradeoffs are worse in general. (They've certainly caused a lot of complexity.) But it doesn't seem quite fair to say that picking a worse set of tradeoffs is broken. (I'm interested in switching to Vitest, but parts of the ecosystem still aren't there for my project.)

I'm happy to accept MSW's decision as to appropriate tradeoffs when using it. (That's what I meant by "making MSW happy"; I apologize if I contributed to any confusion.)

**Comment by mkalvas** [comment] 2023-11-02 18:55
> may I please stress this one last and final time: **You need all this because you are using an OLD testing framework**. Whether you decide to ignore the browser export condition in Node, which is what you should be doing, to begin with, or introduce a custom resolver for Jest—nothing of this has anything to do with MSW. Hope we get this straight in the discussions to come.

Sorry to drag this out more, but this is just not accurate @kettanaito. I understand the technical details of your explanation and the differences between `jest`, `jsdom`, `vitest`, etc. perfectly, so don't mistake this for lack of understanding. There's no need for reiteration of your position, rather there's a need for listening and understanding your users' (valid) choices and circumstances.

Jest and jsdom are not "**OLD**" or outdated. As @joshkel mentioned, they provide a _far more accurate testing environment for browser code_. They are actively maintained and updated. They support the bleeding edge of browser changes and many wide-sweeping libraries and tools.

I've already spent far too much time trying to work around this issue including your suggestion, using other DOM implementations that fall short (such as `happy-dom`), polyfills, resolvers, etc. None of these are fully acceptable and have side effects that impact other correct code outside of `msw`. Please note that just because I was able to get my tests to run and pass, that does not mean that the overall outcome is acceptable.

As such, this is a total blocker for us. We will not be sacrificing the accuracy of our tests in relation to the production environment they'll be running in for one library. Somehow all the thousands of other libraries we use haven't had this issue.

This could be fixed for your users with some action on your part and you're choosing not to. That said, I understand if this is the direction you're taking the library. I'm not asking for anything and I expect nothing in return. I simply wanted to share feedback with you about the entrenched position you've taken that is very clearly not cut and dry like you've painted it.

You spend your time making this awesome tool and I appreciate that, it's just that I'll be unable to continue using it going forward. Thanks for all of your hard work and maybe I'll still be able to use it on some other non-browser project because I really do like it a lot ❤️

**Comment by jd-carroll** [comment] 2023-12-30 01:43
I think I've outline a [solution](https://github.com/mswjs/msw/issues/1809#issuecomment-1872419977) in my [comment](https://github.com/mswjs/msw/issues/1809#issuecomment-1872416267) on #1809.

Would love to be proved wrong (so I can understand why). 

Note: I had to go to levels I am embarrassed to admit in order to come up with this solution. (and it could still be wrong!)

**Comment by jd-carroll** [comment] 2024-01-01 20:59
Nope, my hopes were dashed. The custom resolver solution above is working great for me too.

**Comment by hhsl** [comment] 2024-01-15 17:18
> Please refer to the usage examples with Vitest that feature both ESM and CJS tests, all functional with MSW v2.0:
> 
>     * [Vitest](https://github.com/mswjs/examples/tree/main/examples/with-vitest)
> 
>     * [Vitest CJS](https://github.com/mswjs/examples/tree/main/examples/with-vitest-cjs)
> 
> 
> I've also just migrated the entire internal test suite of MSW to Vitest yesterday without any issues. You don't need to configure JSDOM in any way for Vitest+MSW to work.

Just because I struggled a bit, I wanted to share our solution to this Error because this didn't help in our case while using Vitest. We were trying all attempts described here whithout succes. But then discoverd that the Error was thrown during coverage report generation. Our reporter  "@vitest/coverage-istanbul" apparently looks at everything  INSIDE our `src/` folder, where we also saved our server mocks. So after moving our server mocks OUTSIDE of `src/` the tests ran fine again. 

I also have this little [sandbox](https://codesandbox.io/p/devbox/k2lg2q?file=%2Fvitest.setup.ts&embed=1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clreopupb00062e6aoheg7xhw%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clreopupb00022e6attxnbs20%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clreopupb00032e6awl0pa9j1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clreopupb00052e6aobjbgqoc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60.25216698%252C39.74783302%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clreopupb00022e6attxnbs20%2522%253A%257B%2522id%2522%253A%2522clreopupb00022e6attxnbs20%2522%252C%2522activeTabId%2522%253A%2522clrf35blj00022e692zspmcnx%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clreopupb00012e6agkkphx8w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clrf30o3x00rm2e69g90jc73d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A24%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A24%257D%255D%257D%252C%257B%2522id%2522%253A%2522clrf35blj00022e692zspmcnx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A18%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A18%257D%255D%252C%2522filepath%2522%253A%2522%252Fvitest.setup.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clreopupb00052e6aobjbgqoc%2522%253A%257B%2522id%2522%253A%2522clreopupb00052e6aobjbgqoc%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clreopupb00032e6awl0pa9j1%2522%253A%257B%2522id%2522%253A%2522clreopupb00032e6awl0pa9j1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrf31sud00472e69pdhkdxeg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrf31uvt0014effx57386ad5%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrf31sud00472e69pdhkdxeg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A17.626756261453878%257D) to reproduce this.

**Comment by Fremen1990** [comment] 2024-02-06 23:16
> I have the same issue using `react`, `vite` and `vitest`.
> 
> ```
> "react": "^18.2.0",
> "react-dom": "^18.2.0",
> "@testing-library/jest-dom": "^6.1.4",
> "@testing-library/react": "^14.0.0",
> "vite": "^4.5.0",
> "vitest": "^0.34.6",
> ```
> 
> System: NodeJS : v18.18.2 npm : 9.8.1 OS : macOS 13.5.2

### React Vite Vitest & MSW v2 still doesnt work 😵

I have same problem on React 18, Vite 5.1.0 , Vitest 1.2.2 and MSW 2.0

See no resolution for that on Vite and Vitest config.

I have checked example in Vitest from @kettanaito, but I cannot see the solution there... 

Like @mkalvas  said, there should be separated solution in documentation below Jest solution, as Vitest is huge communitt as well.

https://mswjs.io/docs/migrations/1.x-to-2.x/#cannot-find-module-mswnode-jsdom

Waiting for solution guide for Vitest 🧪

**Comment by andrewbeckman** [comment] 2024-02-08 23:44
> Here's an improved version of my [custom Jest `resolver`](https://github.com/mswjs/msw/issues/1786#issuecomment-1786122056) that replaces `customExportConditions` just for MSW, while leaving Jest's `browser` export for other code that expects it. This allows tests of code that's intended to run in the browser to continue to use the browser versions of other packages, while following MSW's expectation and recommendation of using MSW's Node code within tests.
> 
> ```js
> module.exports = (path, options) => {
>   // Jest + jsdom acts like a browser (i.e., it looks for "browser" imports
>   // under pkg.exports), but msw knows that you're operating in a Node
>   // environment:
>   //
>   // https://github.com/mswjs/msw/issues/1786#issuecomment-1782559851
>   //
>   // The MSW project's recommended workaround is to disable Jest's
>   // customExportConditions completely, so no packages use their browser's
>   // versions.  We'll instead clear export conditions only for MSW.
>   if (/^(msw|@mswjs\/interceptors)(\/|$)/.test(path)) {
>     return options.defaultResolver(path, { ...options, conditions: [] });
>   }
> 
>   return options.defaultResolver(path, options);
> };
> ```
> 
> If this works for others, it may be worth adding as an option in [the docs](https://mswjs.io/docs/migrations/1.x-to-2.x#cannot-find-module-mswnode-jsdom).

@joshkel thanks so much for this! Saved me a ton of time. I made one small tweak to this:

```
if (/^(msw|@mswjs\/interceptors)(\/|$)/.test(path)) {
    return options.defaultResolver(path, {
      ...options,
      conditions: options.conditions.filter(
        (condition) => condition !== "browser"
      ),
    })
}
```

Namely, I left the conditions intact aside from filtering out browser. I'm still early in my testing, but this seems to be working for me and preventing another issue I was running into when I overwrote conditions to be empty.

**Comment by essana3** [comment] 2024-04-07 19:12
Still having the issue with vite, vitest and react...

**Comment by ludwighogstrom** [comment] 2024-05-23 11:51
Got problem in Jest and `@sentry/nextjs` when I upgraded from `@sentry/nextjs@7` to `@sentry/nextjs@8`. Got `Cannot find module '@sentry/nextjs'` with the stack trace
```
at Resolver._throwModNotFoundError (../../node_modules/.pnpm/jest-resolve@29.7.0/node_modules/jest-resolve/build/resolver.js:427:11)
``` 
See discussion here: https://github.com/getsentry/sentry-javascript/issues/10429

It turned out that it was this solution that caused it https://github.com/mswjs/msw/issues/1786#issuecomment-1782559851
```
// jest.config.js 
module.exports = {
  testEnvironmentOptions: {
    customExportConditions: [''],
  }
}
```

When I changed to this solution https://github.com/mswjs/msw/issues/1786#issuecomment-1935104777 with the custom resolver for just MSW, the error disappeared.
```
module.exports = (path, options) => {
  if (/^(msw|@mswjs\/interceptors)(\/|$)/.test(path)) {
    return options.defaultResolver(path, {
      ...options,
      conditions: options.conditions.filter(
        (condition) => condition !== "browser"
      ),
    })
  }

  return options.defaultResolver(path, options);
};
```

**Comment by anandrikka** [comment] 2024-07-10 19:45
> Here's an improved version of my [custom Jest `resolver`](https://github.com/mswjs/msw/issues/1786#issuecomment-1786122056) that replaces `customExportConditions` just for MSW, while leaving Jest's `browser` export for other code that expects it. This allows tests of code that's intended to run in the browser to continue to use the browser versions of other packages, while following MSW's expectation and recommendation of using MSW's Node code within tests.
> 
> ```js
> module.exports = (path, options) => {
>   // Jest + jsdom acts like a browser (i.e., it looks for "browser" imports
>   // under pkg.exports), but msw knows that you're operating in a Node
>   // environment:
>   //
>   // https://github.com/mswjs/msw/issues/1786#issuecomment-1782559851
>   //
>   // The MSW project's recommended workaround is to disable Jest's
>   // customExportConditions completely, so no packages use their browser's
>   // versions.  We'll instead clear export conditions only for MSW.
>   if (/^(msw|@mswjs\/interceptors)(\/|$)/.test(path)) {
>     return options.defaultResolver(path, { ...options, conditions: [] });
>   }
> 
>   return options.defaultResolver(path, options);
> };
> ```
> 
> If this works for others, it may be worth adding as an option in [the docs](https://mswjs.io/docs/migrations/1.x-to-2.x#cannot-find-module-mswnode-jsdom).

[Jest](https://jestjs.io/docs/configuration#testenvironmentoptions-object) provides a built-in way to do this. We still need to add [polyfill](https://mswjs.io/docs/faq/#requestresponsetextencoder-is-not-defined-jest) to work with jsdom
```javascript
const config = {
  testEnvironment: 'jsdom',
  testEnvironmentOptions: {
    customExportConditions: ['msw'],
  },
};
module.exports = config;
```

**Comment by dwjohnston** [comment] 2024-08-30 06:02
> ```js
> module.exports = (path, options) => {
>   // Call the defaultResolver, so we leverage its cache, error handling, etc.
>   return options.defaultResolver(path, {
>     ...options,
>     // Use packageFilter to process parsed `package.json` before the resolution
>     // (see https://www.npmjs.com/package/resolve#resolveid-opts-cb)
>     packageFilter: (pkg) => {
>       if (pkg.name === 'msw') {
>         delete pkg.exports['./node'].browser;
>       }
>       if (pkg.name === '@mswjs/interceptors') {
>         delete pkg.exports;
>       }
> 
>       return pkg;
>     },
>   });
> };
> ```


I found this was the custom resolver I needed to use, but I also needed to use the [jest-fixed-jsdom](https://github.com/mswjs/jest-fixed-jsdom) environment - otherwise you get errors like: 

```
    ReferenceError: TextEncoder is not defined
```

**Comment by mgol** [comment] 2024-10-21 14:45
I was at first thinking about applying the hack from @joshkel at https://github.com/mswjs/msw/issues/1786#issuecomment-1786122056, but I opted to changing the `export` conditions to be just `node` instead, via Jest config:
```js
  testEnvironmentOptions: {
    customExportConditions: ['node'],
  },
```
This is more idiomatic, avoids the need to patch `msw` - which may be brittle - and it's already the default behavior of some other tools like Vitest: https://github.com/vitest-dev/vitest/issues/4757 so I expect this should be quite compatible with the state of npm packages.
