### ISSUE TITLE
FR: GraphQL and HTTP Network Errors

### ISSUE THREAD

**Issue by hinogi** [kettanaito/msw#2394] opened 2024-12-14 12:05 UTC
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Currently when you use graphql you only have one choice of error, and that is a graphql error that comes with the response. If you have a network connectivity error or trying to request from the wrong url or something you'd usually receive a http error.
Currently graphql.query or graphql.mutation do not expect errors from `typeof HttpResponse.error()` although they are possible.
The improvement is to extend the error type for allowed graphql responses to also be of type HttpResponse.error() or compatible.

**Comment by kettanaito** [comment] 2024-12-14 12:07
Thanks for opening this, @hinogi. This appears to be a duplicate of #2130, which even has a pull request open. Please see that issue for more details. Thanks.

**Closed as completed by kettanaito** 2024-12-14 12:07 UTC
Labels: feature
