### ISSUE TITLE
pnpm install msw on Windows fails

### ISSUE THREAD

**Issue by sourceful-wing** [kettanaito/msw#1860] opened 2023-11-15 19:49 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v19.8.1

### Reproduction repository

https://github.com/mswjs/msw

### Reproduction steps

Windows
`pnpm add msw --save-dev`

### Current behavior

$ pnpm add msw --save-dev
Packages: +100
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 101, reused 100, downloaded 0, added 100, done
node_modules/.pnpm/msw@2.0.6/node_modules/msw: Running postinstall script, failed in 24ms
.../.pnpm/msw@2.0.6/node_modules/msw postinstall$ node -e "try{require('./config/scripts/postinstall')}catch(e){}"
│ 'onfig' is not recognized as an internal or external command,
│ operable program or batch file.
└─ Failed in 24ms at C:\Users\[USERNAME]\Documents\Github\test\node_modules\.pnpm\msw@2.0.6\node_modules\msw
 ELIFECYCLE  Command failed with exit code 1.

### Expected behavior

Installation successful. It works with npm but our repo uses pnpm

**Comment by kettanaito** [comment] 2023-11-16 10:44
Hi, @sourceful-wing. Thanks for reporting this. 

Which version of PNPM are you using? 

From the error message, it looks like a parsing bug on PNPM's side. MSW requires a `config/scripts/postinstall` script in its `postinstall` hook, and PNPM, somehow, finds a `'onfig'` string in that require and treats it as a command. I've checked the source and confirm there's no broken requires/commands like that. Moreover, the entire MSW toolchain uses PNPM as well without any issues (we are on 7.12 though).

**Comment by kettanaito** [comment] 2024-01-28 12:54
I'm closing this due to the lack of reproduction. PNPM can install MSW without issues. We are using PNPM to develop MSW. If you encounter any issue, open a new one on GitHub and provide a reproduction scenario. Thanks.

**Closed as completed by kettanaito** 2024-01-28 12:54 UTC
Labels: bug, scope:node, needs:reproduction, needs:triage
