### ISSUE TITLE
Failed to Parse Source Map

### ISSUE THREAD

**Issue by jrock2004** [kettanaito/msw#1070] opened 2022-01-22 16:57 UTC
## Describe the bug
When generate a project using a template I have created that has msw I get a bunch of `Failed to parse source map from`

## Environment

- `msw: 0.36.5`
- `nodejs: 16.13.2`
- `npm: 8.1.2`

> Please also provide your browser version.

## To Reproduce
1. npx create-react-app@latest blog2 --template @jrock2004/cra-template-a11y
2. cd into directory
3. npm run start

## Expected behavior
App runs and nothing in console about warning about source maps

## Example of the output I see

```
Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/createInterceptor.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/createInterceptor.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/index.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/index.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/polyfills/EventPolyfill.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/polyfills/EventPolyfill.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/polyfills/ProgressEventPolyfill.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/polyfills/ProgressEventPolyfill.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/utils/bufferFrom.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/utils/bufferFrom.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/utils/createEvent.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/utils/createEvent.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/remote.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/remote.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/utils/getCleanUrl.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/utils/getCleanUrl.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/utils/parseJson.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/utils/parseJson.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/utils/toIsoResponse.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/utils/toIsoResponse.ts'

Failed to parse source map from '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/utils/uuid.ts' file: Error: ENOENT: no such file or directory, open '/Users/jcostanzo/Development/blog2/node_modules/@mswjs/interceptors/src/utils/uuid.ts'
```

**Comment by washingtonsoares** [comment] 2022-01-24 12:57
Hello! I'm facing the same issue here

![image](https://user-images.githubusercontent.com/5726140/150786646-b7caefa2-e2e2-4de4-ac83-5e301feb6c2d.png)

**Comment by washingtonsoares** [comment] 2022-01-24 14:19
Hi @jrock2004!

I was facing the same issue, and a comment from #1030 solved my problem: https://github.com/mswjs/msw/issues/1030#issuecomment-1001449665

**Comment by kettanaito** [comment] 2022-01-25 15:13
Hey, @jrock2004. This looks like a duplicate of #1030. There's a suggestion on how to circumvent these warnings from @washingtonsoares above. 

We have the issue to publish the source code of `@mswjs/interceptors` to NPM so webpack can build its source maps (see https://github.com/mswjs/interceptors/issues/196). You are welcome to help us with that, if it sounds interesting to you.

**Closed as completed by kettanaito** 2022-01-25 15:13 UTC
Labels: bug
