### ISSUE TITLE
Abort signal not respected for `graphql-request` (v2.4.4+)

### ISSUE THREAD

**Issue by lucademian** [kettanaito/msw#2314] opened 2024-10-11 16:55 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v22.6.0, v20.12.0

### Reproduction repository

https://github.com/lucademian/recursing-snow-4dw63l

### Reproduction steps

npm test

### Current behavior

Tests fail

### Expected behavior

Tests pass

**Comment by kettanaito** [comment] 2024-11-06 10:53
Hi, @lucademian. Thanks for reporting this. 

I've found the root cause and opened a fix at https://github.com/mswjs/interceptors/pull/673. Will propagate to MSW soon.

**Comment by kettanaito** [comment] 2024-11-06 13:00
Re-installing `msw` will pull the latest interceptors version and give you the fix for this issue.

**Closed as completed by kettanaito** 2024-11-06 13:00 UTC
Labels: bug, scope:node
