### ISSUE TITLE
How to do unit testing when using Axios instances?

### ISSUE THREAD

**Issue by victorhcortesp** [kettanaito/msw#1277] opened 2022-06-06 20:06 UTC
### Discussed in https://github.com/mswjs/msw/discussions/1254

<div type='discussions-op-text'>

<sup>Originally posted by **victorhcortesp** May 24, 2022</sup>
I am having trouble getting `msw` to intercept my requests.

I have a configuration file in the root, to get all the environment variables. Something like this
- config.js

```javascript
// config.js

const { BASE_URL } = process.env;

const config = { baseUrl: BASE_URL };

module.exports = config;
```

I have a folder called mocks and inside it I have two files
- handlers.js
NOTE: In the handlers I am performing a stub, the value returned by the config as this baseURL can change depending on the environment variable, so the stub is to ensure that the instance always takes this default value `BASE_URL`.

```javascript
// handlers.js

const { stub } = require('sinon');
const { rest } = require('msw');
const config = require('../config');

const BASE_URL = 'http://localhost:8000';
stub(config, 'baseUrl').value(BASE_URL);

const handlers = [
  rest.post(`${BASE_URL}/positions`, (req, res, ctx) => {
    return res(
      ctx.status(200),
      ctx.json({
        id: 'f79e82e8-c34a-4dc7-a49e-9fadc0979fda',
      })
    );
  })
];

module.exports = { handlers };
```
- server.js
```javascript
// server.js

const { setupServer } = require('msw/node');
const { handlers } = require('./handlers');

const server = setupServer(...handlers);

module.exports = { server };
```

I have another file at a higher level where I create some instances and some functions that use those instances to make the requests. Something like this
```javascript
// instance.js

const axios = require('axios');
const { baseUrl } = require('./config');

const instanceAxios = axios.create({ baseURL: baseUrl });

const addPosition = async (data) => {
  const response = await instanceAxios.post('/positions', data);
  return response.data;
};

module.exports = { addPosition }
```

From this last file I want to do the unit tests, I am trying something like this, but I am not getting the intersection.
```javascript
// instance.test.js

const { server } = require('./mocks/server.js');
const { addPosition } = require('./instance.js');

describe('Axios API', () => {
  beforeAll(() =>
    server.listen({
      onUnhandledRequest: 'warn',  // I added this but it doesn't show me anything, as if it was detecting the route correctly.
    })
  );

  afterEach(() => server.resetHandlers());

  afterAll(() => server.close());

  it('should call axios and return a response', async () => {
    server.printHandlers();  // This is showing me the route configurations fine.
    
    const data = { username: 'username', firstName: 'firstName', lastName: 'lastName' };

    const response = await addPosition(data);

    console.log(response);  // I just want to validate if it is returning the mocked value.
  });
});

```
you can imagine a folder structure similar to this one

```
instance.js
instance.test.js
config.js
mocks
├── server.js
├── handlers.js
```

I would like to know what I am doing wrong or if it is definitely some `msw` problem that does not work very well with axios instances.

### this is the [repository](https://github.com/victorhcortesp/Example-Mock-Service-Worker)</div>

**Comment by kettanaito** [comment] 2022-06-07 08:51
Hi, @victorhcortesp. I'm following up on the matter in the discussion, and closing this issue.

**Closed as completed by kettanaito** 2022-06-07 08:51 UTC

**Comment by eldyvoon** [comment] 2022-08-29 00:54
@kettanaito Why is this closed? having the same issue

**Comment by kettanaito** [comment] 2022-08-29 09:39
It's closed because of [this](https://github.com/mswjs/msw/discussions/1254#discussioncomment-2913433). The fix has been introduced and this issue shouldn't happen given you've updated the library. 

If you still experience this behavior, submit a new issue and don't forget to attach a reproduction repository to prove it.
