### ISSUE TITLE
"browser" folder is empty

### ISSUE THREAD

**Issue by xereda** [kettanaito/msw#1805] opened 2023-10-27 17:10 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/msw

### Reproduction steps

update to latest msw version

### Current behavior

node_modules/msw/browser is empty

### Expected behavior

import of the module to the browser working

**Comment by kettanaito** [comment] 2023-10-27 17:35
Hi, @xereda. Thanks for raising this. 

This is expected, the `/browser`, `/node` and `/native` root-level directories are supposed to be empty. Those exist to provide compatibility with old bundlers and tooling that doesn't understand Node.js export conditions that we have for those paths. 

Is there a particular issue you are experiencing regarding this? It will likely be the configuration issue of tooling and I can try assisting you in that.

**Comment by xereda** [comment] 2023-10-27 18:10
Hi @kettanaito, thanks for your help.

Vscode is showing eslint error when importing setupWorker. 

![image](https://github.com/mswjs/msw/assets/14337850/1f224b42-a4b2-47e7-a720-f133b5f3bb24)

**Comment by kettanaito** [comment] 2023-10-27 18:12
That is a tooling configuration issue. Can you please share a reproduction repository with this? I can tackle this much more efficiently if you do. Also, this seems to be related to #1801. If you are also using Next, it may be a duplicate entirely.

**Comment by xereda** [comment] 2023-10-27 18:12
Yes, I'm using Next.js 14

**Comment by xereda** [comment] 2023-10-27 19:39
@kettanaito Could you recommend migration documentation from a project with MSW 1.3.1 to 2.0.0?

**Comment by xereda** [comment] 2023-10-27 19:43
I found something... https://mswjs.io/docs/migrations/1.x-to-2.x

**Comment by kettanaito** [comment] 2023-10-31 11:10
@xereda, you can find the [Migration guidelines](https://mswjs.io/docs/migrations/1.x-to-2.x) in the docs. 

Next.js 13-14 (App router) doesn't support MSW at the moment. You can follow the discussion and stay updated in #1644. 

Granted, the module resolution issue is likely a different problem than the one mentioned in the ticket.

**Comment by xereda** [comment] 2023-10-31 12:46
@kettanaito Although we are on version 14, we are not using "app router" yet.

**Comment by xereda** [comment] 2023-10-31 12:47
As the migration to version 2 of MSW has breaking changes, we will wait to do this at an opportune time.

**Comment by kettanaito** [comment] 2023-11-03 15:36
@xereda, I have a suspicion to believe that Next.js is fundamentally architectured in a way that prevents tools like MSW from working. You can prove/disprove that statement based on your experience. As of now, I don't guarantee any Next.js compatibility with MSW. 

I am almost sure the solution here is to set up the module resolution correctly and keep the correct `/browser` and `/node `imports. MSW is rather strict about where you import browser- and Node-specific modules, and it forbids wrong imports on the compiler level (the error you are experiencing). This is likely not an MSW issue. This is very likely the project setup issue.

**Comment by kettanaito** [comment] 2023-11-09 11:01
I will close this issue since Next.js 13+ isn't officially supported as of now. I don't wish to spend time on this when the actual MSW integration with Next may be completely different once the Next team decides how to move forward. 

Meanwhile, I highly recommend following #1644 for any updates. Thanks.

**Closed as completed by kettanaito** 2023-11-09 11:01 UTC
Labels: bug, scope:browser, needs:triage

**Comment by xereda** [comment] 2023-11-21 14:56
@kettanaito 

I need to clarify that we have used MSW + Next.js since the beginning of the project and it has always worked very well. We recently migrated to Next.js version 13, but we haven't used the App Router yet. I don't understand when you say that MSW doesn't support Next.js.

In our project, up to version ^1.3.1, MSW works perfectly, even with version 13 of Next.js.

**Comment by xereda** [comment] 2023-11-21 18:00
@kettanaito 

I created a project to exemplify the error with Next.js (without App router).

https://github.com/xereda/nextjs-msw-example

Note the error below:

```
warning ../package.json: No license field
$ next dev
   ▲ Next.js 14.0.3
   - Local:        http://localhost:3000

warning ../package.json: No license field
 ✓ Ready in 2.4s
 ○ Compiling / ...
 ⨯ ./src/mocks/browser.js:2:0
Module not found: Package path ./browser is not exported from package /home/xereda/repositories/nextjs-msw-example/node_modules/msw (see exports field in /home/xereda/repositories/nextjs-msw-example/node_modules/msw/package.json)
  1 | // mocks/browser.js
> 2 | import { setupWorker } from "msw/browser";
  3 | import { handlers } from "./handlers";
  4 |
  5 | if (process.env.NODE_ENV === "development" && typeof window !== "undefined") {

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/pages/_app.js
```
