### ISSUE TITLE
TypeError: Failed to fetch while using redux-toolkit with new msw v. 2.0.0

### ISSUE THREAD

**Issue by bukanidzee** [kettanaito/msw#1794] opened 2023-10-25 13:28 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

18.18.2

### Reproduction repository

https://github.com/bukanidzee/recreate-msw-typeerror

### Reproduction steps

- `npm i`
- `npm run test`

### Current behavior

Test fail and in console we can see `error: { status: 'FETCH_ERROR', error: 'TypeError: Failed to fetch' }` 
I'm not sure if this is msw issue or redux-toolkit-query so I created one for redux-toolkit as well ([#3818](https://github.com/reduxjs/redux-toolkit/issues/3818#issue-1959135458)). I also created [codesandbox](https://codesandbox.io/p/github/bukanidzee/recreate-msw-typeerror/main?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clo5qlfis00073j6i3on55mld%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clo5qlfis00033j6ibzayv6ql%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clo5qlfis00053j6iktbd2jed%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clo5qlfis00063j6ih5g2dk3y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clo5qlfis00033j6ibzayv6ql%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo5qlfir00023j6iq8nzjs7l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clo5qlfis00033j6ibzayv6ql%2522%252C%2522activeTabId%2522%253A%2522clo5qlfir00023j6iq8nzjs7l%2522%257D%252C%2522clo5qlfis00063j6ih5g2dk3y%2522%253A%257B%2522id%2522%253A%2522clo5qlfis00063j6ih5g2dk3y%2522%252C%2522activeTabId%2522%253A%2522clo5rng2x00ju3j6iub05j1o0%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clo5rng2x00ju3j6iub05j1o0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Flogin%2522%257D%255D%257D%252C%2522clo5qlfis00053j6iktbd2jed%2522%253A%257B%2522id%2522%253A%2522clo5qlfis00053j6iktbd2jed%2522%252C%2522activeTabId%2522%253A%2522clo5rx8ss00rs3j6i88dgodjs%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo5qlfis00043j6iuk9dnhvg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clo5qlfof0017ehes38jl80pw%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clo5qlgdr008f3j6ir3t1qmrr%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Fjavascript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clo5qnx6o00bg3j6iix91sk5x%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clo5rx8ss00rs3j6i88dgodjs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clo5rx8uw001lefjthhl6c9rp%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

### Expected behavior

Expect test to run without issues

**Comment by davidgarry** [comment] 2023-10-27 20:40
Hello,

I have the same issue and my setup is almost the same as the one described above by @bukanidzee.

A few more details that could help to understand what is breaking.
- Without the line `beforeAll(() => server.listen())`, the call is correctly done to the real api (this is totally normal).
- When I add the line `beforeAll(() => server.listen())`, I receive the following error : `FetchError: request to xxxxx failed, reason: Cannot read properties of null (reading 'setMaxListeners')`

I hope it will help you to find the issue 🤞

**Comment by mattcosta7** [comment] 2023-11-02 05:08
> Hello,
> 
> I have the same issue and my setup is almost the same as the one described above by [@bukanidzee](https://github.com/bukanidzee).
> 
> A few more details that could help to understand what is breaking.
> 
> * Without the line `beforeAll(() => server.listen())`, the call is correctly done to the real api (this is totally normal).
> * When I add the line `beforeAll(() => server.listen())`, I receive the following error : `FetchError: request to xxxxx failed, reason: Cannot read properties of null (reading 'setMaxListeners')`
> 
> I hope it will help you to find the issue 🤞

> Cannot read properties of null (reading 'setMaxListeners')

this should be fixed in 2.0.2 via https://github.com/mswjs/msw/pull/1813 Not sure if this was the case the original issue had, but if so I expect that is fixed in the new version as well

**Comment by kettanaito** [comment] 2023-11-09 11:20
The `setMaxListeners` issue has been fixed.

Even in 2.0.4 the reproduction repository fails. The reason for that is the relative request URL that ends up being constructed by RTK Query. I believe that is also the reason you are getting the `TypeError: Failed to fetch` forwarded from RTK Query. 

The first thing that struck me odd is if I log anything in the matching handler `http.post('/api/login', resolver)`, nothing gets printed. This means the handler _doesn't match_. But how can that be?

I then added a permissive `http.all()` handler which will match absolutely all outgoing traffic in the test:

```js
http.post('*', () => {
  console.log('If this is not printed, request did not actually happen')
}),
```

This wasn't printed. This indicates that the `FETCH_ERROR` you are getting indicates a rejected request—the one that didn't even occur. 

I suspect that the reason for that rejection is you constructing a _relative_ endpoint URL while running your tests in Node.js. That's a no-op. No relative URLs in Node.js—nothing to be relative to. See https://github.com/reduxjs/redux-toolkit/issues/3284 for more details. 

Once you configure your `baseUrl` to be absolute, the handlers are matched correctly and the resolver sends whichever response you defined:

```diff
baseQuery: fetchBaseQuery({
-  baseUrl: '/api',
+  baseUrl: new URL('/api', location.origin).href,
}),
```

The test still fails but I suspect something is off with the implementation, for both `data` and `error` remain undefined. I can confirm the handler matches, so it sends the response. You can look into it further to see if there are any issues with your fetching logic.

**Closed as completed by kettanaito** 2023-11-09 11:20 UTC
Labels: bug, scope:node, needs:triage

**Comment by jimbolla-th** [comment] 2023-12-08 15:03
We were also running into the `Cannot read properties of null (reading 'setMaxListeners')` error when upgrading to MSW 2. The culprit for us was the `cross-fetch` polyfill in our test setup that we still had for running on older versions of Node. Removing `cross-fetch` eliminated the problem.

**Comment by israrkhan002n** [comment] 2023-12-26 13:54
In my case the handler is getting called but still i am getting the above issue
this is the response i am getting 
{
    requestId: '1xingaItFOOG99Y7v8wnO',
    status: 'rejected',
    endpointName: 'addBanner',
    startedTimeStamp: 1703598624590,
    error: { status: 'FETCH_ERROR', error: 'TypeError: Failed to fetch' },
    isUninitialized: false,
    isLoading: false,
    isSuccess: false,
    isError: true,
    originalArgs: FormData {},
    reset: [Function (anonymous)]
  }
