### ISSUE TITLE
URL Field not found in RestRequest in RestFunction.

### ISSUE THREAD

**Issue by minsgy** [kettanaito/msw#1903] opened 2023-12-01 15:45 UTC
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Hello, I'm using msw well.

When you upgrade the existing MSW version from v0.49.1 to v1.3.2, you see that the Request type definition provided by the Rest feature has changed.

So a code such as 'req.url' fails to deduce the type and an error mark appears. How can we resolve this?

Error Code: `The type 'RestRequest<never, PathParams<string>' has no 'url' property.`

The error statement appears and does not work using type affirmation.

![image](https://github.com/mswjs/msw/assets/60251579/e6f5dfbf-c9f2-4876-bb50-cb3d7ce8f580)

**Comment by minsgy** [comment] 2023-12-01 15:46
Oh, I'm sorry. I couldn't change the label status

**Comment by mattcosta7** [comment] 2023-12-01 16:52
@minsgy can you make a sample of this?

I just attempted to recreate and I cannot. see https://stackblitz.com/edit/vitejs-vite-ylekkx?file=src%2Fmain.tsx

**Comment by mattcosta7** [comment] 2023-12-01 16:54
closing because I believe it is working correctly in that version, however if you can create a reproduction of the issue i'm happy to take a look.

**Closed as completed** 2023-12-02 02:11 UTC
Labels: feature
