### ISSUE TITLE
TypeError: Failed to execute 'append' on 'Headers': String contains non ISO-8859-1 code point.

### ISSUE THREAD

**Issue by Jungzl** [kettanaito/msw#1814] opened 2023-11-01 07:20 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

nah

### Reproduction steps

![image](https://github.com/mswjs/msw/assets/35426360/548c8047-26f4-4baa-aca5-46013e99b4c6)

### Current behavior

If cookie has ISO-8859-1 code point, it will throw error like above.

### Expected behavior

no error.

**Comment by kettanaito** [comment] 2023-11-01 15:45
Thanks for opening this. Looks like a duplicate of #1808. I also left a [comment](https://github.com/mswjs/msw/pull/1815#issuecomment-1789189911) on the pull request, suggesting that it may be a good idea to handle this on the consumer's side instead.

**Closed as completed by kettanaito** 2023-11-01 15:45 UTC
Labels: bug, scope:browser, needs:triage

**Comment by kettanaito** [comment] 2023-11-16 11:16
## Released: v2.0.7 🎉

This has been released in v2.0.7!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.0.7)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.0.7)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
