### ISSUE TITLE
Message still persists after updating

### ISSUE THREAD

**Issue by ofirgellerSM** [kettanaito/msw#1083] opened 2022-01-29 04:45 UTC
## Describe the bug

Running `npx msw init public` generates a file with checksum '02f4ad4a2797f85668baf196e553d929'.
During runtime msw reports an error saying:
`Detected outdated Service Worker: Currently active Service Worker (02f4ad4a2797f85668baf196e553d929) is behind the latest published one (f0a916b13c8acc2b526a03a6d26df85f).`

## Environment

- `msw: 0.36.7`
- yarn 1.22.5
 
## To Reproduce
1. run `npx msw init public`
2. check for errors in browser dev console

**Comment by kettanaito** [comment] 2022-01-30 11:23
Hey, @ofirgellerSM. 

The latest published worker hashsum is indeed `02f4ad4a2797f85668baf196e553d929` ([confirmation](https://unpkg.com/msw@0.36.7/lib/umd/mockServiceWorker.js)). 

I think what's happening is that `npx msw` picks up the latest MSW version while your local version in `node_modules/msw` is still an old one. 

Could you please verify you've installed 0.36.7 _locally_?

```sh
npm ls msw
```

You can always do `npm i msw@latest --save-dev` to be sure. Thanks.

**Comment by kettanaito** [comment] 2022-01-31 14:42
I'm closing this because it's very likely to be caused by the `msw` versions mismatch between the locally installed version and the `npx msw` version. Please prove me wrong by providing a reproduction repository where we can take a look at this issue. Thanks.

**Closed as completed by kettanaito** 2022-01-31 14:42 UTC
Labels: bug, needs:discussion, potentially solved

**Comment by maddhruv** [comment] 2023-06-06 16:23
For me it wasn't getting fixed by running `msw init`, had to do a clean node_modules install to make it work
