### ISSUE TITLE
Malformed binary response in fallback mode

### ISSUE THREAD

**Issue by quirk0o** [kettanaito/msw#1106] opened 2022-02-17 15:12 UTC
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.36.3   |
| browser | IE 11     |
| OS      | Windows 10     |

## Request handlers

```js
// MSW handler.
import { setupWorker, rest } from 'msw'
import image from './files/image.png'

const respondWithFile = file => async (req, res, ctx) => {
  const buffer = await ctx.fetch(file).then(res => res.arrayBuffer())

  return res(ctx.set('Content-Length', buffer.byteLength.toString()), ctx.body(buffer))
}

const worker = setupWorker(
   rest.get(`${apiUrl()}/image.png`, respondWithFile(image))
)

worker.start()
```

## Actual request

```js
// Making a request
axios
    .get(url, {
      responseType: 'blob'
    })
    .then(res => res.data)
    .then(readAsBuffer)

const readAsBuffer = async blob => {
  const reader = new FileReader()

  const result = new Promise((resolve, reject) => {
    reader.addEventListener('error', () => reject('Could not read as buffer'))
    reader.addEventListener('loadend', () => resolve(reader.result))
  })

  reader.readAsArrayBuffer(blob)

  return result
}
```

## Current behavior

On IE 11 the byte length of the binary response is sometimes larger and sometimes smaller than the actual file and the `Content-Length` header. The file is malformed and cannot be parsed. 

In Chrome, the file is sent correctly and the returned buffer has the correct size. I've tested this on images and the image can be displayed correctly in Chrome but not in IE 11 (in the actual code base this is a data block and not an image).

This also happens with responses coming from another server that bypass MSW (so the actual file is sent from an external source but seems to get malformed when coming through the MSW interceptor. I've also tested on IE with the external server without MSW - the responses are correct in that case,

## Expected behavior
The returned response is the same as the file sent from the handler.

**Comment by kettanaito** [comment] 2022-03-06 17:45
Hey, @quirk0o. Thanks for reporting this. 

As the issue seems to manifest in IE11, it may be caused by how the browser is handling things. 

Frankly, I don't even know what to suggest. The fallback mode is rather basic `window.fetch` stub where we intercept a [request](https://github.com/mswjs/interceptors/blob/97a04bc6178bc3d20853cba5a4b559d9d4cdc494/src/interceptors/fetch/index.ts#L29-L36) you perform and await the [mocked response](https://github.com/mswjs/interceptors/blob/97a04bc6178bc3d20853cba5a4b559d9d4cdc494/src/interceptors/fetch/index.ts#L41) and [create a `Response` instance](https://github.com/mswjs/interceptors/blob/97a04bc6178bc3d20853cba5a4b559d9d4cdc494/src/interceptors/fetch/index.ts#L50-L56) out of it. Response transformers like `ctx.set()` simply modify the `Headers` instance, so I wouldn't suspect anything going on there. 

For triage, can you see what is the output of `buffer.byteLength.toString()` across browsers? If that number fluctuates, then the issue is how `fetch` calculates buffer length in IE11 and there's little we can do about it. MSW itself is rather transparent, creating standard `Response` instances and not bringing much custom logic to the table. 

I will close this because I don't see this as an MSW issue. We also do not provide support for IE at all: nothing is tested in IE. MSW is a devtool and you should strive towards using the latest tools with it (including browsers).

**Closed as completed by kettanaito** 2022-03-06 17:45 UTC
Labels: bug, scope:browser
