### ISSUE TITLE
getaddrinfo ENOTFOUND in Node.js tests

### ISSUE THREAD

**Issue by rcffc** [kettanaito/msw#1449] opened 2022-11-04 09:18 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

16.18.0

### Reproduction repository

https://github.com/rcffc/msw-problem/

### Reproduction steps

Run `npm i ` followed by `node test.ts`

### Current behavior

1. Handlers are not printed.
2. Address could not be resolved, since it's an example address it suggests that the request is not mocked, which is supported by 1).

```
[rest] /.+/ https://api.backend.dev/user
  Declaration: /home/taro/projects/onefleet-worktrees/dev/B/services/location/node_modules/msw/lib/index.js:962:36

Error: getaddrinfo ENOTFOUND api.backend.dev
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.backend.dev'
}
```

### Expected behavior

1. Handler should be printed.
2. Should be mocked
3. Response should be 200

**Comment by kettanaito** [comment] 2022-11-04 18:03
Hey, @rcffc. Thanks for reporting this. I will take a look once I have a minute.

**Comment by andreydrozd** [comment] 2022-11-18 15:01
On my project that had msw at the latest release version, 0.48.3, I too had the same issue. My project also has vitest and I see projects that have vitest have had issues as well [have had issues as well](https://github.com/mswjs/msw/issues/1319). 

I had to make the following changes to my dependencies to make everything work.

``` json
 ...
  "msw": "0.43.1",
  "vitest": "0.17.1"
  },
  "overrides": {
    "msw": {
      "headers-polyfill": "3.0.9"
    },
    "@mswjs/interceptors": {
      "headers-polyfill": "3.0.9"
    }
  }
```

**Comment by juancampuzano** [comment] 2023-02-10 12:51
@kettanaito Any update on this issue?

**Comment by kettanaito** [comment] 2023-02-10 14:05
@juancampuzano, nope. I didn't have time to look into this. I'm head-deep with #1464 so I'm unlikely to visit this issue in the foreseeable future. Anybody is welcome to debug this and share their findings. 

@andreydrozd, thanks for sharing that! If the issue indeed lies in the `headers-polyfill` version, then I recommend applying those overrides for the time being. We will release the updated dependency on that library with the next Interceptors dependency, which is also a part of the Fetch API endeavor.

**Comment by juancampuzano** [comment] 2023-03-14 10:41
In my case the problem was related to the **fetch** library I was using.
 
In the beginning, I was using this library **[isomorphic-unfetch](https://www.npmjs.com/package/isomorphic-unfetch)**

- import 'isomorphic-unfetch'
- **Node 16.18.0**

After updating Node to 18.14.0 I need to change the fetch library to  **[cross-fetch](https://github.com/lquixada/cross-fetch)**

- import fetch from "cross-fetch";
- **Node 18.14.0**

I know it's not a definitive solution but it could solve the problem and save a lot of time.

**Comment by kettanaito** [comment] 2023-11-14 09:43
@juancampuzano, not that you _don't need to use any fetch polyfills_ on Node.js 18. It comes with the global fetch build-in. 

I'm closing this issue because it's not reproducible with MSW 2.0 + Node.js v18+. I highly encourage anyone reading this to migrate to modern tooling.

**Closed as completed by kettanaito** 2023-11-14 09:43 UTC
Labels: bug, help wanted, scope:node, needs:triage
