### ISSUE TITLE
Error: "Failed to execute 'text' on 'Response': body stream already read"

### ISSUE THREAD

**Issue by petrovmiroslav** [kettanaito/msw#1660] opened 2023-07-14 17:21 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/petrovmiroslav/msw-simultaneous-requests-bug

### Reproduction steps

Hello everyone! First of all, thank you for the library!
I've faced with a problem recently. If I send two requests at the same time, I get an error "Uncaught (in promise) TypeError: Failed to execute 'text' on 'Response': body stream already read". Could anyone tell me what am I doing wrong?

### Steps to reproduce:
1. npm install
2. npm start

### Current behavior

Error message:
```
serializeResponse.ts:14 
Uncaught (in promise) TypeError: Failed to execute 'text' on 'Response': body stream already read
    at serializeResponse (serializeResponse.ts:14:1)
    at Emitter.<anonymous> (createRequestListener.ts:77:1)
    at Emitter.onceListener (Emitter.js:40:1)
    at Emitter.js:75:1
    at Array.forEach (<anonymous>)
    at Emitter.emit (Emitter.js:74:1)
    at source.emit (pipeEvents.ts:19:1)
    at createResponseListener.ts:32:1
    at ServiceWorkerContainer.<anonymous> (setupWorker.ts:93:1)
```

### Expected behavior

The error doesn't appear

**Comment by kettanaito** [comment] 2023-07-18 08:27
Hi, @petrovmiroslav. Thanks for reporting this!

This issue looks like a duplicate of #1640. I will close it in favor of the mentioned issue. Please follow the discussion and progress on it there. Thanks.

**Closed as completed by kettanaito** 2023-07-18 08:27 UTC
Labels: bug, scope:browser, needs:triage
