### ISSUE TITLE
Cannot find module msw/node after updating

### ISSUE THREAD

**Issue by joshbenhamou** [kettanaito/msw#1960] opened 2024-01-10 16:49 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

21.4.0

### Reproduction repository

https://github.com/mswjs/examples/tree/main/examples/with-vitest

### Reproduction steps

The issue is happening in the official MSW Vitest example. Check out the sandbox link and see the typescript error https://codesandbox.io/p/sandbox/github/mswjs/examples-new/tree/main/examples/with-vitest?file=%2Fmocks%2Fnode.ts%3A2%2C32-3%2C1

### Current behavior

Import validation fails

### Expected behavior

Import validation succeeds

**Comment by kettanaito** [comment] 2024-01-15 09:57
Hi, @joshbenhamou. I've just updated all the examples to the latest version of MSW and they all pass. Could you please confirm your issue is solved?

**Comment by joshbenhamou** [comment] 2024-01-22 20:06
Thanks @kettanaito . The sandbox link is no longer working for me in https://github.com/mswjs/examples/tree/main/examples/with-vitest. However, I saw that you updated the MSW package to 2.0.14 and tried that locally. Same problem with that version and also with 2.1.3

**Comment by kettanaito** [comment] 2024-01-25 12:45
Oh, thanks for pointing out the broken sandboxes! Caused by renaming the repo and deleting the old one. Will fix. 

_Edit:_ the sandbox is running properly now but it doesn't seem CodeSandbox allows us to use terminal anymore to run tests. You may want to check that example locally.

**Comment by joshbenhamou** [comment] 2024-01-26 15:36
Thanks. The sandbox is working for me now. It looks like the change you've made that is the `module` and `moduleResolution` in the `tsconfig.json`. Trying this locally, raises typescript errors across every import. I need to look into this further but happy for you to close the issue as it's working on the demo. If you could explain a little behind the rationale of the compiler option changes that'd be nice though

**Comment by iChip** [comment] 2024-01-26 18:09
I'm experiencing the same issue, but no changes to module/moduleResolution seem to resolve it in my project.

I do notice that the sandbox is a major version behind on both vitest and resolved vite version.. that being said, after bumping these, I still cannot reproduce the issue in the sandbox 🙃

**Comment by erichartline** [comment] 2024-01-31 20:04
I'm also running into the same issue using Node v18.19.0 and MSW v2.1.5. I tried modifying my `tsconfig.json` file to match what's shown in the example but that didn't help. Any ideas?

**Comment by joshbenhamou** [comment] 2024-02-02 13:14
Same as @iChip , it's still not working for me but I haven't had the time to investigate yet unfortunately

**Comment by sampolahtinen** [comment] 2024-04-22 08:59
Same thing happens for me. My setup is Remix, Cloudflare Workers, Playwright with following configs:

```json
    ...
    "moduleResolution": "Bundler",
    "module": "ES2022",
    "resolveJsonModule": true,
    "target": "ES2022",
    ...
```

```ts
/** @type {import('@remix-run/dev').AppConfig} */
export default {
  ignoredRouteFiles: [`**/.*`],
  server: `./app/server.ts`,
  serverConditions: ['workerd', 'worker', 'browser'],
  serverDependenciesToBundle: [
    // bundle everything except the virtual module for the static content manifest provided by wrangler
    /^(?!.*\b__STATIC_CONTENT_MANIFEST\b).*$/,
  ],
  serverMainFields: [`browser`, `module`, `main`],
  serverMinify: true,
  serverModuleFormat: `esm`,
  serverPlatform: `neutral`,
  browserNodeBuiltinsPolyfill: {
    modules: {
      buffer: true,
    },
  },
  serverNodeBuiltinsPolyfill: {
    modules: ['util', 'crypto'],
  },
}

```

Do we have any ideas what might be the cause? 

I am willing to give a stab and fixing it if there is a person who could point me to a direction!

**Comment by DamienDeloubes** [comment] 2024-05-02 19:48
Just want to chime and and mention I am upgrading MSW from 1.3.3 to 2.2.13 and receive the same error

```cmd
Package path ./node is not exported from package /Users/damien/Documents/Git/Maia/monorepo/node_modules/msw (see exports field in /Users/damien/Documents/Git/Maia/monorepo/node_modules/msw/package.json)
```

My scripts is very basic

```js
import { setupServer, type SetupServer } from 'msw/node';

import { handlers } from './handlers';

export const server: SetupServer = setupServer(...handlers);
```

**Comment by erichartline** [comment] 2024-05-07 13:59
I'm also running into the same issue after upgrading. My use case is to mock out API responses for components using Storybook and the MSW addon. I tried upgrading everything together -- MSW to v2, msw-storybook-addon to v2, Storybook from v7 to v8 -- but no matter what I try I'm getting the same error as @DamienDeloubes.

I tried the [hacky solution](https://github.com/mswjs/msw/issues/1801#issuecomment-1793911389) mentioned in another issue but that still caused errors with any component's Storybook file that was using the MSW addon. I've tried adjusting my `tsconfig.json` and tweaking my Storybook Webpack config to no avail. I'm also not using the app router so there's no conflict there. Does anyone have any other ideas?

**Comment by NateWilliams2** [comment] 2024-05-07 19:24
IDK if this will help you, but I had a similar issue and found that the hacky solution only worked if I removed the `!isServer` clause, i.e. not adding an alias for 'msw/node' for the client build. I posted my solution at https://github.com/mswjs/msw/issues/1877#issuecomment-2099139075

**Comment by erichartline** [comment] 2024-05-07 21:01
> IDK if this will help you, but I had a similar issue and found that the hacky solution only worked if I removed the `!isServer` clause, i.e. not adding an alias for 'msw/node' for the client build. I posted my solution at [#1877 (comment)](https://github.com/mswjs/msw/issues/1877#issuecomment-2099139075)

Thanks for the idea. Unfortunately, I'm still getting the `Package path ./node is not exported from package node_modules/msw` when trying to access any stories using MSW. I've tried every variation of the Webpack config I can think of to no avail. Glad you were able to find a solution though!

**Comment by kettanaito** [comment] 2024-05-08 18:06
With the help from @phryneas, we've done some improvements in the export conditions in MSW. Please upgrade to `msw@2.3.0` and let me know if you still experience the `Package path ./node is not exported from package node_modules/msw` error. Thanks!

**Comment by DamienDeloubes** [comment] 2024-05-13 07:41
> With the help from @phryneas, we've done some improvements in the export conditions in MSW. Please upgrade to `msw@2.3.0` and let me know if you still experience the `Package path ./node is not exported from package node_modules/msw` error. Thanks!

Hmm, I still seem to encounter the same error when pinning the msw package to 2.3.0.

```
Module not found: Package path ./node is not exported from package /Users/damien/Documents/Git/Maia/monorepo/node_modules/msw (see exports field in /Users/damien/Documents/Git/Maia/monorepo/node_modules/msw/package.json)
```

**Comment by erichartline** [comment] 2024-05-13 14:26
I am also still receiving the same error when trying to run/build Storybook (which uses MSW pretty heavily).

**Comment by phryneas** [comment] 2024-05-13 18:23
You will still need to ensure that you have a `node` import condition specified in your bundler setup - but now, it will work with both `node` and `browser` specified, where before it only worked if you had only `node` (without `bundler`) specified.

**Comment by DamienDeloubes** [comment] 2024-05-14 12:22
> ```js
> import { setupServer, type SetupServer } from 'msw/node';
> 
> import { handlers } from './handlers';
> 
> export const server: SetupServer = setupServer(...handlers);
> ```

Thanks for your input! What do you mean exactly? For example, I am working in a NextJS repository with MSW used for mocking endpoints. The setup looks fairly straightforward, this has always worked for us:

```js
import { setupServer, type SetupServer } from 'msw/node';

import { handlers } from './handlers';

export const server: SetupServer = setupServer(...handlers);
```

However, I am still encountering the build issue as described above. How would I go about resolving that issue?

**Comment by phryneas** [comment] 2024-05-14 17:39
Are you using vitest?
Here's an example [vite.config.js](https://github.com/apollographql/apollo-client-nextjs/blob/main/integration-test/vitest/vite.config.js):

```js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  resolve: {
    // this line is important so the "browser build" of dependencies is used
    // and not the "SSR build", which would contain "streaming-to-the-browser"
    // specific code
   // "node" is important so it picks up the right msw import.
    conditions: ["browser", "node"],
  },
  test: {
    globals: true,
    environment: "jsdom",
  },
});
```

**Comment by DamienDeloubes** [comment] 2024-05-14 17:46
Unfortunately not vite, just a plain NextJS project

**Comment by phryneas** [comment] 2024-05-14 18:01
So you are trying to mock the network access inside of React Server Components? I'm not sure if that's supported. Also, afaik Next.js simulates their edge runtime in some cases - not sure if you can mock anything in that environment.

**Comment by DamienDeloubes** [comment] 2024-05-14 18:08
Sorry, I see I was a bit unclear. I have a NextJS project where I use Redux Toolkit Query. For the past year, I have used MSW to make the requests made by RTQ. Unfortunately when I upgraded the MSW package I got the error described in this thread, moving back to an older version fixes everything. So I don't want to mock server components, just the rtq apis.

**Comment by phryneas** [comment] 2024-05-14 18:33
So, still pages router. Maybe @kettanaito knows something on how to set that up - you'll need some additional bundler config.

**Comment by kettanaito** [comment] 2024-05-15 14:09
Next.js uses webpack, so you have to add a `webpack` property in `next.config.js` and add the `node` condition to webpack's module resolution logic:

```js
// next.config.js
module.exports = {
  webpack(config) {
    config.resolve.conditionNames = ['node', ...webpackDefaultConditions]
  }
}
```

> [`resolve.conditionNames`](https://webpack.js.org/configuration/resolve/#resolveconditionnames)

The above is made-up, you have to read Next.js docs if that's the right way to extend webpack.

**Comment by hnipps** [comment] 2024-08-09 19:07
Having the same issue in a React, Vite, Jest project. Although the setup works for our React Native app (RN/Metro/Jest) 🤔

**Comment by hnipps** [comment] 2024-08-09 19:16
Setting `customExportConditions` to `'node'` seems to have fixed the issue for me.
```ts
testEnvironment: 'jest-environment-jsdom',
testEnvironmentOptions: {
  customExportConditions: ['node'],
},
```

Full Jest config:
```ts
import type { Config } from 'jest';

const config: Config = {
  cacheDirectory: '.jest/cache',
  collectCoverage: true,
  collectCoverageFrom: ['<rootDir>/src/**/*.{js,jsx,ts,tsx}', '!<rootDir>/src/**/env-variables.ts'],
  coverageReporters: ['lcov'],
  moduleDirectories: ['node_modules', 'src', 'test'],
  testMatch: ['<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}', '<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}'],
  moduleNameMapper: {
    '\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/__mocks__/filemock.ts',
    '\\.(css|less)$': '<rootDir>/__mocks__/filemock.ts',
  },
  setupFiles: ['<rootDir>/jest.polyfills.js'],
  setupFilesAfterEnv: ['<rootDir>/mock-api/setup.js'], // MSW setup file
  testEnvironment: 'jest-environment-jsdom',
  testEnvironmentOptions: {
    customExportConditions: ['node'],
  },
};

export default config;
```

The [default `customExportCondition` is `'browser'`](https://jestjs.io/docs/configuration#testenvironmentoptions-object) and I believe this caused Jest module resolver to look at the `browser` key in the `./node` block of MSW package.json exports, which is set to `null`. Hence the "Cannot find module" error.

By setting `customExportConditions` to `'node'` we tell the module resolver to look at the `node` key of the `./node` block in package.json exports, which leads us to the correct module 🎉

**Comment by erichartline** [comment] 2024-08-13 02:38
> I am also still receiving the same error when trying to run/build Storybook (which uses MSW pretty heavily).

An update from my end - I was able to bypass this issue by avoiding importing any mock handler functions from files that were also importing from `msw/node`. Even though I wasn't using anything from `msw/node` directly, my Storybook builds would still break. By separating the functions from any references to the node version of the mock server, I was able to get past the issue.

**Comment by kettanaito** [comment] 2024-10-23 19:11
I'm going to close this because there's no action needed on MSW's side. You are still welcome to post your questions or findings. 

Export conditions are, sadly, not handled correctly in a lot of tools. If you are using Jest, use https://github.com/mswjs/jest-fixed-jsdom. In other tooling, make sure that the `node` export condition is used when in Node.js (e.g. in a test process or on the server). 

I also highly encourage raising an issue with the tools that fail to resolve `msw/node`. That's likely indicative that they don't have the export conditions configured correctly.

**Closed as completed by kettanaito** 2024-10-23 19:11 UTC
Labels: bug, potentially solved, scope:node, needs:triage
