### ISSUE TITLE
"InvalidStateError: The object is in invalid state" when mocking rest api

### ISSUE THREAD

**Issue by Lespoir** [kettanaito/msw#2089] opened 2024-03-15 22:36 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v18.15.0

### Reproduction repository

No Repo

### Reproduction steps

Versions:
- "react-native": "0.71.11"
- "msw": "2.2.3"
- "undici": "5.22.0"

Setup:
- Polyfill file created with:
```
const { TextDecoder, TextEncoder } = require('node:util')

Object.defineProperties(globalThis, {
    TextDecoder: { value: TextDecoder },
    TextEncoder: { value: TextEncoder },
})

const { Blob } = require('node:buffer')
const { fetch, Headers, FormData, Request, Response } = require('undici')

Object.defineProperties(globalThis, {
    fetch: { value: fetch, writable: true },
    Blob: { value: Blob },
    Headers: { value: Headers },
    FormData: { value: FormData },
    Request: { value: Request },
    Response: { value: Response },
})
```
Steps:
- Add a rest handler like
```
server.use(
    rest.post(`/test`, () =>
      HttpResponse.json({}),
    ),
  );
```
- Create a test that checks the mock is called

### Current behavior

Getting this error:
```
detail: Invariant Violation: InvalidStateError: The object is in invalid state.
          at next (/Users/davidavila/Documents/gg/core-mobile/node_modules/@mswjs/interceptors/src/utils/createProxy.ts:81:24)
          at Object.handler.get (/Users/davidavila/Documents/gg/core-mobile/node_modules/@mswjs/interceptors/src/utils/createProxy.ts:86:11)
          at onloadend (/Users/davidavila/Documents/gg/core-mobile/node_modules/axios/lib/adapters/xhr.js:101:17)
          at Timeout.task [as _onTimeout] (/Users/davidavila/Documents/gg/core-mobile/node_modules/jsdom/lib/jsdom/browser/Window.js:520:19)
          at listOnTimeout (node:internal/timers:569:17)
          at processTimers (node:internal/timers:512:7),
```

### Expected behavior

Test should pass

**Comment by kettanaito** [comment] 2024-05-08 17:53
Hey, @Lespoir. Thanks for reporting this. Please try out the new version of MSW, I think this has been fixed in the underlying dependency library. If the issue persists, please provide a reproduction repository. I cannot help here without having a code to dive in. Thanks.

**Closed as completed by kettanaito** 2024-05-08 17:53 UTC
Labels: bug, scope:node, needs:triage

**Comment by miso-belica** [comment] 2024-05-14 15:40
I believe this error happens when using Axios in Jest because MSW assumes `responseType` should be `'text'` or empty string in https://github.com/mswjs/interceptors/blob/8ba00cad812f50a489a16522f31a40af90fa86f1/src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts#L437 but Axios is calling `request.responseText` for `responseType === 'json'` in https://github.com/axios/axios/blob/b9f4848f8c4c7d53dbe1a1ee06e9b3604c2e56ac/lib/adapters/xhr.js#L46-L47

I think invariant in MSW changed to be more strict causing this. Even though it's in line with the spec. Solution is to abandon Axios and use `fetch()` or something like https://github.com/developit/redaxios which does not use`XMLHttpRequest`.
