### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by surapuramakhil** [kettanaito/msw#1647] opened 2023-06-28 19:34 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Firefox

### Reproduction repository

https://github.com/mswjs/msw

### Reproduction steps

enabling msw me landing tho the bellow error.

tried looking for creating reproduction repo but coudn't find sample for vue2

### Current behavior

Module parse failed: Unexpected token (312:4)
You may need an appropriate loader to handle this file type.
|   headers.set("x-msw-bypass", "true");
|   return {
|     ...requestInit,
|     headers: headers.all()
|   };

 @ ./src/mocks/browser.js 2:0-34
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

### Expected behavior

MSW show be working as expected

**Comment by kettanaito** [comment] 2024-01-21 12:18
Hi, @surapuramakhil. You've reported this bug on MSW 1.x. We've since improved the library with the 2.x release, which I highly recommend you upgrade to. 

- [2.0 announcement post](https://mswjs.io/blog/introducing-msw-2.0)
- [Migration guide](https://mswjs.io/docs/migrations/1.x-to-2.x)
- [Common issues](https://mswjs.io/docs/migrations/1.x-to-2.x#frequent-issues)

Once you migrate to 2.x, this issue should be fixed. If it's not, please open a new one and provide a _reproduction repository_. Without it, any reported issues will be closed. Thanks.

**Closed as completed by kettanaito** 2024-01-21 12:18 UTC
Labels: bug, scope:browser, needs:triage
