### ISSUE TITLE
terminate() throws; am I doing something wrong?

### ISSUE THREAD

**Issue by Lord-Kamina** [kettanaito/msw#1515] opened 2023-01-09 19:03 UTC
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

16.18.0

### Reproduction repository

https://github.com/Lord-Kamina/always-upload-cache/tree/update-tests

### Reproduction steps

./node_modules/.bin/tsc --noEmit && ./node_modules/.bin/jest --coverage --runInBand=true --verbose=true --testLocationInResults=true --testNamePattern OctoKit

### Current behavior

Error:
```
 RUNS  __tests__/actionUtils.test.ts
/Users/Koji/always-upload-cache/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js:385
        this.agent.destroy();
                   ^

TypeError: Cannot read properties of undefined (reading 'destroy')
    at NodeClientRequest.Object.<anonymous>.NodeClientRequest.terminate (/Users/Koji/always-upload-cache/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:361:16)
    at NodeClientRequest.Object.<anonymous>.NodeClientRequest.respondWith (/Users/Koji/always-upload-cache/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:353:10)
    at /Users/Koji/always-upload-cache/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:164:14
```

### Expected behavior

Either works or doesn't, but I don't think it should throw?

Note: that repo is probably a mess, as I essentially only committed my working copy to a branch, in order to post this issue.

**Comment by kettanaito** [comment] 2023-01-11 15:50
Hey, @Lord-Kamina. Thanks for reporting this. 

You're certainly not doing anything wrong. It looks like the `agent` is not defined in this particular case. I'd like to look into the reproduction case and see how come HTTP agent is undefined (to my best knowledge that's a no-op in Node). And still, I've seen so many libraries torturing Node API that I'm hard to impress these days. 

Will look into this once I have a minute and will let you know.

**Comment by Lord-Kamina** [comment] 2023-01-11 17:49
I replied in the other repo. In a nutshell, updating to Node v19.4 solved it (still not working but for unrelated reasons, will ask about it if I can't solve it) so it seems to be version dependent?

**Comment by kettanaito** [comment] 2023-01-13 19:15
Closing in favor of [304](https://github.com/mswjs/interceptors/issues/304). This isn't an issue with MSW directly.

**Closed as completed by kettanaito** 2023-01-13 19:15 UTC
Labels: bug, scope:node, needs:triage
